#include "skin_changer.h"


void skins::change()
{
	CEntity* local_player = interfaces::EntityList->GetClientEntityFromID(interfaces::engine->GetLocalPlayerIndex());

	

	if (!local_player)
		return;


	int* weapons = (int*)(local_player + offsets::m_hMyWeapons);

    skins::change_knife_model();


	for (int index = 0; index < 64; index++)
	{
		CEntity* weapon = interfaces::EntityList->GetClientEntityFromHandle((int)weapons[index]);
		CWeapon_Entity* weapon_entity = (CWeapon_Entity*)weapon;

		if (!weapon)
		{
			continue;
		}

		int list_ID = skins::get_list_index(weapon_entity);

		if (!list_ID) continue;


        
		weapon_entity->SetPaintKit(settings::skins[list_ID].ID, settings::skins[list_ID].weapon_float);

	}

	
}


void skins::change_knife_model()
{
    CEntity* local_player = interfaces::EntityList->GetClientEntityFromID(interfaces::engine->GetLocalPlayerIndex());

    if (!local_player)
        return;

    int model_index = interfaces::g_pModelInfo->GetModelIndex("models/weapons/v_knife_karam.mdl");

    if (!model_index)
    {
        std::cout << "fake model index" << std::endl;
        return;

    }

    int weapon_type = local_player->GetActiveWeapon()->GetWeaponType();

    if (weapon_type != CEntity::WEAPONTYPE_KNIFE)
        return;

    CBaseViewModel* viewModel = (CBaseViewModel*)interfaces::EntityList->GetClientEntityFromHandle(local_player->GetViewModelHandle());

    //CEntity* worldModel = interfaces::EntityList->GetClientEntityFromHandle(*(int*)(viewModel + 0x3254));


    if (!viewModel)
        return;

    *(viewModel->GetModelIndexPointer()) = model_index;
    *(local_player->GetActiveWeapon()->GetModelIndexPointer()) = model_index;
    *(int*)(local_player->GetActiveWeapon() + offsets::m_iItemDefinitionIndex) = WEAPON_KNIFE_KARAMBIT;
  
    ((CWeapon_Entity*)(local_player->GetActiveWeapon()))->SetPaintKit(settings::skins[KNIFE].ID, settings::skins[KNIFE].weapon_float);
   



    
    
   

}

void skins::update()
{
	interfaces::engine->ClientCmd("record x; stop;");
}

void skins::pop_skin_list()
{
	for (int i = 0; i < 35; i++)
	{
		skin_settings x = { 0, 0.00001f };
		settings::skins.push_back(x);
	}
}

int skins::get_list_index(CWeapon_Entity* weapon_entity)
{
	if (((CEntity*)weapon_entity)->GetWeaponType() == 1) // checks if its a glock cuz famas and glock have same id
		if (weapon_entity->GetWeaponID() == 10)
			return GLOCK;

	switch (weapon_entity->GetWeaponID())
	{
	case WEAPON_DEAGLE:
		return DEAGLE;
	case WEAPON_ELITE:
		return DUALEES;
	case WEAPON_FIVESEVEN:
		return FIVESEVEN;
	case WEAPON_AK47:
		return AK47;
	case WEAPON_AUG:
		return AUG;
	case WEAPON_AWP:
		return AWP;
	case WEAPON_FAMAS:
		return FAMAS;
	case WEAPON_G3SG1:
		return G3SG1;
	case WEAPON_GALILAR:
		return GALIL;
	case WEAPON_M249:
		return M249;
	case WEAPON_M4A1_SILENCER:
		return M4A1;
	case WEAPON_MAC10:
		return MAC10;
	case WEAPON_P90:
		return P90;
	case WEAPON_MP5SD:
		return MP5;
	case WEAPON_UMP45:
		return UMP;
	case WEAPON_XM1014:
		return XM;
	case WEAPON_BIZON:
		return PPBIZON;
	case WEAPON_MAG7:
		return MAG7;
	case WEAPON_NEGEV:
		return NEGEV;
	case WEAPON_SAWEDOFF:
		return SAWEDOFF;
	case WEAPON_TEC9:
		return TEC;
	case WEAPON_HKP2000:
		return P2000;
	case WEAPON_MP7:
		return MP7;
	case WEAPON_MP9:
		return MP9;
	case WEAPON_NOVA:
		return NOVA;
	case WEAPON_P250:
		return P250;
	case WEAPON_SCAR20:
		return SCAR;
	case WEAPON_SG556:
		return SG;
	case WEAPON_SSG08:
		return SSG;
	case WEAPON_KNIFE:
		return KNIFE;
	case WEAPON_CZ75A:
		return CZ;
	case WEAPON_REVOLVER:
		return REVOLVER;
	case WEAPON_USP_SILENCER:
		return USPS;
	}

	return 0;
}

int skins::skinEnumToID(int SkinEnum) 
{
    switch (SkinEnum){
    case THIRDRDCOMMANDOCOMPANY:
        return 10080;
    case ABYSS:
        return 361;
    case ABYSSALAPPARITION:
        return 1133;
    case ACHERON:
        return 788;
    case ACIDETCHED:
        return 951;
    case ACIDFADE:
        return 253;
    case ACIDWASH:
        return 888;
    case AERIAL:
        return 598;
    case AFTERIMAGE:
        return 154;
    case AGENT:
        return 915;
    case AIRLOCK:
        return 609;
    case AKIHABARAACCEPT:
        return 455;
    case AKOBEN:
        return 649;
    case AKOBEN_1:
        return 842;
    case ALLURE:
        return 965;
    case ALOHA:
        return 665;
    case ALOHA_1:
        return 702;
    case AMBERFADE:
        return 246;
    case AMBERFADE_1:
        return 523;
    case AMBERSLIPSTREAM:
        return 708;
    case AMPHIBIOUS:
        return 10045;
    case ANCIENTEARTH:
        return 1020;
    case ANCIENTLORE:
        return 1021;
    case ANCIENTRITUAL:
        return 1034;
    case ANCIENTVISIONS:
        return 1031;
    case ANGRYMOB:
        return 837;
    case ANODIZEDGUNMETAL:
        return 210;
    case ANODIZEDNAVY:
        return 28;
    case ANODIZEDNAVY_1:
        return 197;
    case ANOLIS:
        return 829;
    case ANTIQUE:
        return 286;
    case ANTIQUE_1:
        return 306;
    case APEPSCURSE:
        return 1248;
    case APOCALYPTO:
        return 953;
    case AQUATERRACE:
        return 460;
    case AQUAMARINEREVENGE:
        return 474;
    case ARBOREAL:
        return 10056;
    case ARCTICCAMO:
        return 6;
    case ARCTICWOLF:
        return 704;
    case ARCTICWOLF_1:
        return 886;
    case ARID:
        return 10019;
    case ARISTOCRAT:
        return 583;
    case ARMORCORE:
        return 423;
    case ARMYMESH:
        return 242;
    case ARMYRECON:
        return 245;
    case ARMYSHEEN:
        return 298;
    case ASHWOOD:
        return 234;
    case ASIIMOV:
        return 255;
    case ASIIMOV_1:
        return 279;
    case ASIIMOV_2:
        return 359;
    case ASIIMOV_3:
        return 551;
    case ASIIMOV_4:
        return 801;
    case ASSAULT:
        return 914;
    case ASTERION:
        return 442;
    case ASTRALJÖRMUNGANDR:
        return 759;
    case ATHERIS:
        return 838;
    case ATLAS:
        return 553;
    case ATOMICALLOY:
        return 301;
    case AUTOTRONIC:
        return 573;
    case AUTOTRONIC_1:
        return 574;
    case AUTOTRONIC_2:
        return 575;
    case AUTOTRONIC_3:
        return 576;
    case AUTOTRONIC_4:
        return 577;
    case AUTOTRONIC_5:
        return 1114;
    case AUTOTRONIC_6:
        return 1115;
    case AUTOTRONIC_7:
        return 1116;
    case AUTOTRONIC_8:
        return 1117;
    case AUTOTRONIC_9:
        return 1118;
    case AUTUMNTWILLY:
        return 1061;
    case AVALANCHE:
        return 520;
    case AZTEC:
        return 902;
    case AZUREGLYPH:
        return 1251;
    case AZUREZEBRA:
        return 229;
    case BADLANDS:
        return 10036;
    case BALANCE:
        return 895;
    case BAMBOOFOREST:
        return 459;
    case BAMBOOGARDEN:
        return 872;
    case BAMBOOPRINT:
        return 457;
    case BAMBOOSHADOW:
        return 458;
    case BAMBOOZLE:
        return 839;
    case BANANACANNON:
        return 1232;
    case BANANALEAF:
        return 731;
    case BAROQUEORANGE:
        return 746;
    case BAROQUEPURPLE:
        return 745;
    case BAROQUERED:
        return 744;
    case BARRICADE:
        return 861;
    case BASILISK:
        return 383;
    case BENGALTIGER:
        return 9;
    case BENGALTIGER_1:
        return 1030;
    case BERRIESANDCHERRIES:
        return 1002;
    case BI83SPECTRUM:
        return 1089;
    case BIGGAME:
        return 10074;
    case BIGIRON:
        return 503;
    case BIOLEAK:
        return 549;
    case BLACKTAN:
        return 928;
    case BLACKLAMINAT_10:
        return 1113;
    case BLACKLAMINATE:
        return 172;
    case BLACKLAMINATE_1:
        return 563;
    case BLACKLAMINATE_2:
        return 564;
    case BLACKLAMINATE_3:
        return 565;
    case BLACKLAMINATE_4:
        return 566;
    case BLACKLAMINATE_5:
        return 567;
    case BLACKLAMINATE_6:
        return 1109;
    case BLACKLAMINATE_7:
        return 1110;
    case BLACKLAMINATE_8:
        return 1111;
    case BLACKLAMINATE_9:
        return 1112;
    case BLACKLIMBA:
        return 190;
    case BLACKLOTUS:
        return 1102;
    case BLACKNILE:
        return 1239;
    case BLACKSAND:
        return 629;
    case BLACKSAND_1:
        return 697;
    case BLACKSAND_2:
        return 814;
    case BLACKSAND_3:
        return 891;
    case BLACKTIE:
        return 557;
    case BLACKTIE_1:
        return 10072;
    case BLASTFROMTHEPAST:
        return 1024;
    case BLAZE:
        return 37;
    case BLAZEORANGE:
        return 166;
    case BLEACHED:
        return 934;
    case BLINDSPOT:
        return 228;
    case BLIZZARDMARBLEIZED:
        return 75;
    case BLOODINTHEWATER:
        return 222;
    case BLOODPRESSURE:
        return 10079;
    case BLOODTIGER:
        return 217;
    case BLOODSHOT:
        return 899;
    case BLOODSPORT:
        return 597;
    case BLOODSPORT_1:
        return 639;
    case BLOODSPORT_2:
        return 696;
    case BLOOMSTICK:
        return 62;
    case BLUEFISSURE:
        return 278;
    case BLUELAMINATE:
        return 226;
    case BLUEPHOSPHOR:
        return 1017;
    case BLUEPLY:
        return 945;
    case BLUESPRUCE:
        return 96;
    case BLUESTEEL:
        return 42;
    case BLUESTREAK:
        return 13;
    case BLUETIRE:
        return 1078;
    case BLUETITANIUM:
        return 216;
    case BLUEPRINT:
        return 642;
    case BLUEPRINT_1:
        return 657;
    case BONEFORGED:
        return 952;
    case BONEMACHINE:
        return 370;
    case BONEMASK:
        return 27;
    case BONEPILE:
        return 193;
    case BOOM:
        return 174;
    case BOOME:
        return 10027;
    case BOOSTPROTOCOL:
        return 1093;
    case BOREALFOREST:
        return 77;
    case BOROQUESAND:
        return 920;
    case BRAKELIGHT:
        return 797;
    case BRASS:
        return 159;
    case BRATATAT:
        return 317;
    case BREAKERBOX:
        return 1083;
    case BRIAR:
        return 330;
    case BRIEFING:
        return 615;
    case BRIEFING_1:
        return 663;
    case BRIGHTWATER:
        return 189;
    case BRIGHTWATER_1:
        return 578;
    case BRIGHTWATER_2:
        return 579;
    case BRONZEDECO:
        return 425;
    case BRONZEMORPH:
        return 10046;
    case BRONZED:
        return 10008;
    case BROTHER:
        return 964;
    case BUCKSHOT:
        return 10062;
    case BUDDY:
        return 906;
    case BULKHEAD:
        return 783;
    case BULLDOZER:
        return 39;
    case BULLETQUEEN:
        return 957;
    case BULLETRAIN:
        return 155;
    case BUNSENBURNER:
        return 479;
    case BUSINESSCLASS:
        return 364;
    case BUTTONMASHER:
        return 1045;
    case BUZZKILL:
        return 632;
    case CAGEDSTEEL:
        return 299;
    case CAIMAN:
        return 339;
    case CALFSKIN:
        return 748;
    case CALICAMO:
        return 240;
    case CANALSPRAY:
        return 866;
    case CANDYAPPLE:
        return 3;
    case CANDYAPPLE_1:
        return 864;
    case CAPILLARY:
        return 646;
    case CAPILLARY_1:
        return 715;
    case CAPILLARY_2:
        return 943;
    case CARAMEL:
        return 93;
    case CARBONFIBER:
        return 70;
    case CARDIAC:
        return 391;
    case CARNIVORE:
        return 589;
    case CARTEL:
        return 388;
    case CARTEL_1:
        return 394;
    case CARTEL_2:
        return 528;
    case CARVEDJADE:
        return 1033;
    case CASEHARDENED:
        return 44;
    case CASEHARDENED_1:
        return 10060;
    case CASSETTE:
        return 968;
    case CATACOMBS:
        return 399;
    case CAUTION:
        return 1071;
    case CAUTION_1:
        return 10084;
    case CERBERUS:
        return 379;
    case CHAINMAIL:
        return 327;
    case CHALICE:
        return 325;
    case CHAMELEON:
        return 280;
    case CHANTICOSFIRE:
        return 548;
    case CHARRED:
        return 10006;
    case CHARTER:
        return 994;
    case CHATTERBOX:
        return 398;
    case CHECKENGINE:
        return 796;
    case CHEMICALGREEN:
        return 376;
    case CHOPPER:
        return 593;
    case CHROMATICABERRATION:
        return 1038;
    case CHROMATICABERRATION_1:
        return 1144;
    case CHRONOS:
        return 438;
    case CINQUEDEA:
        return 737;
    case CIRCAETUS:
        return 1036;
    case CIRRUS:
        return 627;
    case CLASSICCRATE:
        return 908;
    case CLAYAMBUSH:
        return 1014;
    case CLEARPOLYMER:
        return 987;
    case CLEARPOLYMER_1:
        return 1039;
    case CO_PROCESSOR:
        return 781;
    case COACHCLASS:
        return 346;
    case COBALTCORE:
        return 499;
    case COBALTDISRUPTION:
        return 231;
    case COBALTHALFTONE:
        return 267;
    case COBALTQUARTZ:
        return 249;
    case COBALTSKULLS:
        return 10053;
    case COBRASTRIKE:
        return 658;
    case COCOARAMPAGE:
        return 977;
    case CODERED:
        return 711;
    case COLDBLOODED:
        return 67;
    case COLDFUSION:
        return 790;
    case COLONY:
        return 47;
    case COLONYIV:
        return 897;
    case COMMEMORATION:
        return 919;
    case COMMUTER:
        return 343;
    case CONDEMNED:
        return 110;
    case CONDITIONZERO:
        return 986;
    case CONNEXION:
        return 972;
    case CONSPIRACY:
        return 351;
    case CONSTRICTOR:
        return 10083;
    case CONTAINMENTBREACH:
        return 887;
    case CONTAMINANT:
        return 982;
    case CONTAMINATION:
        return 373;
    case CONTRACTOR:
        return 46;
    case CONTRASTSPRAY:
        return 22;
    case CONTROLPANEL:
        return 792;
    case CONVERTER:
        return 793;
    case CONVOY:
        return 10015;
    case COOLMINT:
        return 10028;
    case COOLANT:
        return 784;
    case COPPER:
        return 41;
    case COPPERBORRE:
        return 761;
    case COPPERCOATED:
        return 1245;
    case COPPERGALAXY:
        return 274;
    case COPPERHEAD:
        return 10;
    case COREBREACH:
        return 787;
    case CORINTHIAN:
        return 509;
    case CORPORAL:
        return 281;
    case CORTEX:
        return 705;
    case CORTICERA:
        return 181;
    case CORTICERA_1:
        return 184;
    case COUNTERTERRACE:
        return 462;
    case CRACKEDOPAL:
        return 684;
    case CRAZY8:
        return 1145;
    case CRIMESCENE:
        return 1003;
    case CRIMSONBLOSSOM:
        return 729;
    case CRIMSONKIMONO:
        return 466;
    case CRIMSONKIMONO_1:
        return 10033;
    case CRIMSONTSUNAMI:
        return 647;
    case CRIMSONWEAVE:
        return 10016;
    case CRIMSONWEB:
        return 12;
    case CRIMSONWEB_1:
        return 232;
    case CRIMSONWEB_2:
        return 10061;
    case CRYPSIS:
        return 835;
    case CURSE:
        return 310;
    case CUTOUT:
        return 671;
    case CYANOSPATTER:
        return 92;
    case CYBERSECURITY:
        return 985;
    case CYBERSHELL:
        return 1044;
    case CYBERFORCE:
        return 1234;
    case CYREX:
        return 312;
    case CYREX_1:
        return 360;
    case CYREX_2:
        return 487;
    case CYREX_3:
        return 637;
    case DAEDALUS:
        return 444;
    case DAMASCUSSTEEL:
        return 247;
    case DAMASCUSSTEEL_1:
        return 410;
    case DAMASCUSSTEEL_2:
        return 411;
    case DAMASCUSSTEEL_3:
        return 857;
    case DAMASCUSSTEEL_4:
        return 858;
    case DANGERCLOSE:
        return 815;
    case DARKAGE:
        return 329;
    case DARKBLOSSOM:
        return 730;
    case DARKFILIGREE:
        return 741;
    case DARKWATER:
        return 60;
    case DARKWING:
        return 955;
    case DART:
        return 386;
    case DAYLILY:
        return 725;
    case DAYBREAK:
        return 471;
    case DAZZLE:
        return 610;
    case DEADLYPOISON:
        return 403;
    case DEATHBYKITTY:
        return 156;
    case DEATHBYPUPPY:
        return 913;
    case DEATHGRIP:
        return 669;
    case DEATHRATTLE:
        return 293;
    case DEATHSTRIKE:
        return 1052;
    case DEATHSHEAD:
        return 670;
    case DECIMATOR:
        return 644;
    case DECIMATOR_1:
        return 889;
    case DECOMMISSIONED:
        return 904;
    case DEEPRELIEF:
        return 983;
    case DELUSION:
        return 392;
    case DEMETER:
        return 195;
    case DEMOLITION:
        return 153;
    case DESERTBLOSSOM:
        return 765;
    case DESERTBRUSH:
        return 924;
    case DESERTDDPAT:
        return 925;
    case DESERTHYDRA:
        return 819;
    case DESERTSHAMAGH:
        return 10081;
    case DESERTSTORM:
        return 8;
    case DESERTSTRIKE:
        return 949;
    case DESERTTACTICAL:
        return 1253;
    case DESERTWARFARE:
        return 311;
    case DESERT_STRIKE:
        return 336;
    case DESERT_STRIKE_1:
        return 355;
    case DESOLATESPACE:
        return 588;
    case DESTROYER:
        return 1147;
    case DETOUR:
        return 319;
    case DEV_TEXTURE:
        return 1043;
    case DEVOURER:
        return 720;
    case DEZASTRE:
        return 978;
    case DIAMONDBACK:
        return 10040;
    case DIGITALARCHITECT:
        return 1081;
    case DIGITALMESH:
        return 980;
    case DIRECTIVE:
        return 603;
    case DIRTDROP:
        return 753;
    case DISCOTECH:
        return 947;
    case DISPATCH:
        return 997;
    case DISTRESSED:
        return 944;
    case DJINN:
        return 429;
    case DOOMKITTY:
        return 178;
    case DOPPLE_10:
        return 852;
    case DOPPLE_11:
        return 853;
    case DOPPLE_12:
        return 854;
    case DOPPLE_13:
        return 855;
    case DOPPLER:
        return 415;
    case DOPPLER_1:
        return 416;
    case DOPPLER_2:
        return 417;
    case DOPPLER_3:
        return 418;
    case DOPPLER_4:
        return 419;
    case DOPPLER_5:
        return 420;
    case DOPPLER_6:
        return 421;
    case DOPPLER_7:
        return 617;
    case DOPPLER_8:
        return 618;
    case DOPPLER_9:
        return 619;
    case DOWNTOWN:
        return 1148;
    case DRAGONLORE:
        return 344;
    case DRAGONTATTOO:
        return 48;
    case DRAGONTECH:
        return 1151;
    case DRAGONFIRE:
        return 624;
    case DREAMGLADE:
        return 1129;
    case DRIFTWOOD:
        return 824;
    case DROPME:
        return 1152;
    case DROUGHT:
        return 825;
    case DRYSEASON:
        return 199;
    case DUALINGDRAGONS:
        return 491;
    case DUALITY:
        return 1222;
    case DUCTTAPE:
        return 10055;
    case DUELIST:
        return 447;
    case DUSKRUINS:
        return 1032;
    case ECHOINGSANDS:
        return 1244;
    case ECLIPSE:
        return 10024;
    case ECO:
        return 428;
    case ECO_1:
        return 709;
    case ELECTRICHIVE:
        return 227;
    case ELEGANTVINES:
        return 821;
    case ELITE16:
        return 903;
    case ELITEBUILD:
        return 422;
    case ELITEBUILD_1:
        return 486;
    case ELITEBUILD_2:
        return 525;
    case EMBARGO:
        return 884;
    case EMERALD:
        return 196;
    case EMERALDDRAGON:
        return 182;
    case EMERALDJÖRMUNGANDR:
        return 757;
    case EMERALDPINSTRIPE:
        return 300;
    case EMERALDPOISONDART:
        return 648;
    case EMERALDQUARTZ:
        return 859;
    case EMERALDWEB:
        return 10034;
    case EMERALD_1:
        return 453;
    case EMERALD_2:
        return 10057;
    case EMPHOROSAUR_S:
        return 1223;
    case ENFORCER:
        return 954;
    case ENSNARED:
        return 1131;
    case ENTOMBED:
        return 970;
    case EVILDAIMYO:
        return 480;
    case EXCHANGER:
        return 786;
    case EXO:
        return 590;
    case EXOSKELETON:
        return 975;
    case EXPOSURE:
        return 688;
    case EYEOFATHENA:
        return 723;
    case EYEOFHORUS:
        return 1255;
    case FACETS:
        return 207;
    case FACILITYDARK:
        return 778;
    case FACILITYDRAFT:
        return 777;
    case FACILITYNEGATIVE:
        return 776;
    case FACILITYSKETCH:
        return 775;
    case FADE:
        return 38;
    case FADE_1:
        return 522;
    case FADE_2:
        return 752;
    case FADE_3:
        return 879;
    case FADE_4:
        return 1026;
    case FADE_5:
        return 10063;
    case FADEDZEBRA:
        return 176;
    case FAIRYTALE:
        return 979;
    case FALLHAZARD:
        return 1082;
    case FALLOUTWARNING:
        return 169;
    case FALLOUTWARNING_1:
        return 378;
    case FAULTYWIRING:
        return 1066;
    case FEATHERWEIGHT:
        return 1225;
    case FENNECFOX:
        return 764;
    case FEVERDREAM:
        return 640;
    case FEVERDREAM_1:
        return 956;
    case FIELDAGENT:
        return 10068;
    case FINISHLINE:
        return 10077;
    case FIREELEMENTAL:
        return 389;
    case FIRESERPENT:
        return 180;
    case FIREFIGHT:
        return 546;
    case FIRESTARTER:
        return 385;
    case FIRSTCLASS:
        return 341;
    case FIRSTCLASS_1:
        return 345;
    case FIZZYPOP:
        return 1059;
    case FLAMEJÖRMUNGANDR:
        return 758;
    case FLAMETEST:
        return 693;
    case FLASHOUT:
        return 905;
    case FLASHBACK:
        return 631;
    case FLASHBACK_1:
        return 817;
    case FLEETFLOCK:
        return 541;
    case FLORACARNIVORA:
        return 1156;
    case FLUX:
        return 493;
    case FOODCHAIN:
        return 1037;
    case FORESIGHT:
        return 1132;
    case FORESTDDPAT:
        return 5;
    case FORESTDDPAT_1:
        return 10030;
    case FORESTLEAVES:
        return 25;
    case FORESTNIGHT:
        return 78;
    case FOUNDATION:
        return 10035;
    case FOWLPLAY:
        return 352;
    case FRAGMENTS:
        return 1226;
    case FRAMEWORK:
        return 1076;
    case FRANKLIN:
        return 295;
    case FRANKLIN_1:
        return 1016;
    case FREEHAND:
        return 580;
    case FREEHAND_1:
        return 581;
    case FREEHAND_2:
        return 582;
    case FREIGHT:
        return 969;
    case FRONTSIDEMISTY:
        return 490;
    case FROSTBORRE:
        return 760;
    case FUBAR:
        return 552;
    case FUBAR_1:
        return 816;
    case FUELINJECTOR:
        return 524;
    case FUELINJECTOR_1:
        return 614;
    case FUELROD:
        return 508;
    case FULLSTOP:
        return 250;
    case GAMMADOPPLER:
        return 568;
    case GAMMADOPPLER_1:
        return 569;
    case GAMMADOPPLER_2:
        return 570;
    case GAMMADOPPLER_3:
        return 571;
    case GAMMADOPPLER_4:
        return 572;
    case GAMMADOPPLER_5:
        return 1119;
    case GAMMADOPPLER_6:
        return 1120;
    case GAMMADOPPLER_7:
        return 1121;
    case GAMMADOPPLER_8:
        return 1122;
    case GAMMADOPPLER_9:
        return 1123;
    case GATORMESH:
        return 243;
    case GAUSS:
        return 846;
    case GHOSTCAMO:
        return 225;
    case GHOSTCRUSADER:
        return 554;
    case GILA:
        return 634;
    case GIRAFFE:
        return 10082;
    case GLACIERMESH:
        return 111;
    case GLOBALOFFENSIVE:
        return 993;
    case GNARLED:
        return 960;
    case GOLDARABESQUE:
        return 921;
    case GOLDBISMUTH:
        return 990;
    case GOLDBRICK:
        return 1025;
    case GOLDENCOIL:
        return 497;
    case GOLDENKOI:
        return 185;
    case GOO:
        return 679;
    case GRANDPRIX:
        return 436;
    case GRANITEMARBLEIZED:
        return 21;
    case GRAPHITE:
        return 212;
    case GRAPHITE_1:
        return 214;
    case GRASSLAND:
        return 95;
    case GRASSLANDLEAVES:
        return 104;
    case GRAVEN:
        return 188;
    case GREENAPPLE:
        return 294;
    case GREENLAMINATE:
        return 1070;
    case GREENMARINE:
        return 502;
    case GREENPLAID:
        return 366;
    case GRIFFIN:
        return 384;
    case GRIM:
        return 611;
    case GRINDER:
        return 381;
    case GRIP:
        return 701;
    case GROTTO:
        return 406;
    case GROUNDWATER:
        return 2;
    case GROUNDWATER_1:
        return 209;
    case GUARDIAN:
        return 257;
    case GUARDIAN_1:
        return 290;
    case GUERRILLA:
        return 1096;
    case GUERRILLA_1:
        return 10039;
    case GUNGNIR:
        return 756;
    case GUNSMOKE:
        return 15;
    case HADES:
        return 439;
    case HANDBRAKE:
        return 751;
    case HANDCANNON:
        return 328;
    case HANDGUN:
        return 485;
    case HARDWATER:
        return 666;
    case HARVESTER:
        return 594;
    case HAZARD:
        return 198;
    case HAZARDPAY:
        return 1084;
    case HEADSHOT:
        return 1221;
    case HEAT:
        return 284;
    case HEAT_1:
        return 431;
    case HEAVENGUARD:
        return 291;
    case HEAVENGUARD_1:
        return 314;
    case HEAVYMETAL:
        return 1048;
    case HEDGEMAZE:
        return 10038;
    case HEIRLOOM:
        return 273;
    case HEIST:
        return 1005;
    case HELLFIRE:
        return 664;
    case HEMOGLOBIN:
        return 220;
    case HEXANE:
        return 218;
    case HIEROGLYPH:
        return 1254;
    case HIGHBEAM:
        return 799;
    case HIGHROLLER:
        return 676;
    case HIGHSEAS:
        return 712;
    case HIGHWAYMAN:
        return 390;
    case HIVE:
        return 219;
    case HOTROD:
        return 33;
    case HOTROD_1:
        return 445;
    case HOTSHOT:
        return 377;
    case HOTSNAKES:
        return 1009;
    case HOUNDSTOOTH:
        return 1008;
    case HOWL:
        return 309;
    case HUMIDOR:
        return 827;
    case HUNTER:
        return 677;
    case HUNTINGBLIND:
        return 241;
    case HYDRA:
        return 910;
    case HYDROPONIC:
        return 456;
    case HYPERBEAST:
        return 430;
    case HYPERBEAST_1:
        return 475;
    case HYPERBEAST_2:
        return 537;
    case HYPERBEAST_3:
        return 660;
    case HYPNOTIC:
        return 61;
    case ICARUSFELL:
        return 440;
    case ICECAP:
        return 599;
    case ICECOALED:
        return 1143;
    case IMMINENTDANGER:
        return 1073;
    case IMPACTDRILL:
        return 472;
    case IMPERIAL:
        return 515;
    case IMPERIALDRAGON:
        return 591;
    case IMPERIALPLAID:
        return 10042;
    case IMPIRE:
        return 536;
    case IMPRINT:
        return 602;
    case INLIVINGCOLOR:
        return 1041;
    case INCINEGATOR:
        return 850;
    case INDIGO:
        return 333;
    case INFERNO:
        return 907;
    case INFRASTRUCTURE:
        return 1080;
    case INLAY:
        return 1237;
    case INSOMNIA:
        return 1220;
    case INTEGRALE:
        return 750;
    case INTERLOCK:
        return 1077;
    case IRONCLAD:
        return 592;
    case IRONWORK:
        return 623;
    case IRRADIATEDALERT:
        return 171;
    case ISAAC:
        return 303;
    case IVORY:
        return 357;
    case JADE:
        return 10085;
    case JAGUAR:
        return 316;
    case JAMBIYA:
        return 539;
    case JETSET:
        return 340;
    case JUDGEMENTOFANUBIS:
        return 542;
    case JUNGLE:
        return 151;
    case JUNGLEDASHED:
        return 147;
    case JUNGLEDDPAT:
        return 202;
    case JUNGLESLIPSTREAM:
        return 641;
    case JUNGLESLIPSTREAM_1:
        return 685;
    case JUNGLESPRAY:
        return 122;
    case JUNGLETHICKET:
        return 870;
    case JUNGLETIGER:
        return 16;
    case JUNGLE_1:
        return 205;
    case JUNKYARD:
        return 1047;
    case JUSTICE:
        return 948;
    case KAMI:
        return 265;
    case KAMI_1:
        return 308;
    case KEEPINGTABS:
        return 1095;
    case KILLCONFIRMED:
        return 504;
    case KINGSNAKE:
        return 10041;
    case KISSLOVE:
        return 1155;
    case KITBASH:
        return 974;
    case KNIGHT:
        return 326;
    case KOI:
        return 356;
    case KUMICHODRAGON:
        return 527;
    case LABRATS:
        return 800;
    case LABYRINTH:
        return 362;
    case LAPISGATOR:
        return 534;
    case LASTDIVE:
        return 651;
    case LEADCONDUIT:
        return 540;
    case LEADEDGLASS:
        return 681;
    case LEATHER:
        return 342;
    case LEATHER_1:
        return 10009;
    case LEETMUSEO:
        return 1087;
    case LEGIONOFANUBIS:
        return 959;
    case LICHENDASHED:
        return 26;
    case LIFTEDSPIRITS:
        return 1138;
    case LIGHTRAIL:
        return 841;
    case LIGHTNINGSTRIKE:
        return 51;
    case LIMELIGHT:
        return 596;
    case LIONFISH:
        return 698;
    case LIQUIDATION:
        return 1231;
    case LLAMACANNON:
        return 683;
    case LORE:
        return 558;
    case LORE_1:
        return 559;
    case LORE_2:
        return 560;
    case LORE_3:
        return 561;
    case LORE_4:
        return 562;
    case LORE_5:
        return 1104;
    case LORE_6:
        return 1105;
    case LORE_7:
        return 1106;
    case LORE_8:
        return 1107;
    case LORE_9:
        return 1108;
    case LOUDMOUTH:
        return 483;
    case LTCOMMANDER:
        return 10066;
    case LUMEN:
        return 1099;
    case LUNARWEAVE:
        return 10013;
    case LUSHRUINS:
        return 1022;
    case MACABRE:
        return 659;
    case MAGMA:
        return 266;
    case MAGNACARTA:
        return 1028;
    case MAGNESIUM:
        return 811;
    case MAINFRAME:
        return 780;
    case MAINFRAME001:
        return 967;
    case MALACHITE:
        return 402;
    case MAN_O_WAR:
        return 395;
    case MAN_O_WAR_1:
        return 432;
    case MANDREL:
        return 785;
    case MANGROVE:
        return 10058;
    case MARBLEFADE:
        return 413;
    case MARBLEFADE_1:
        return 856;
    case MARBLEFADE_2:
        return 10065;
    case MARINA:
        return 261;
    case MASTERPIECE:
        return 321;
    case MAYANDREAMS:
        return 200;
    case MECHAINDUSTRIES:
        return 587;
    case MECHAINDUSTRIES_1:
        return 626;
    case MECHAINDUSTRIES_2:
        return 805;
    case MECHANISM:
        return 1085;
    case MEDUSA:
        return 446;
    case MEHNDI:
        return 258;
    case MELONDRAMA:
        return 1126;
    case MELTDOWN:
        return 1053;
    case MEMENTO:
        return 177;
    case MEMENTO_1:
        return 892;
    case MEOW36:
        return 1146;
    case METALFLOWERS:
        return 672;
    case METALLICDDPAT:
        return 34;
    case METEORITE:
        return 296;
    case MIDNIGHTLILY:
        return 727;
    case MIDNIGHTPALM:
        return 933;
    case MIDNIGHTSTORM:
        return 468;
    case MINOTAURSLABYRINTH:
        return 441;
    case MINTKIMONO:
        return 467;
    case MISCHIEF:
        return 847;
    case MJÖLNIR:
        return 763;
    case MODERNHUNTER:
        return 164;
    case MODESTTHREAT:
        return 804;
    case MODULE:
        return 335;
    case MOGUL:
        return 10064;
    case MOMENTUM:
        return 802;
    case MOMENTUM_1:
        return 845;
    case MONKEYBUSINESS:
        return 427;
    case MONKEYFLAGE:
        return 1150;
    case MONSTERCALL:
        return 961;
    case MONSTERMASHUP:
        return 991;
    case MOONINLIBRA:
        return 450;
    case MOONRISE:
        return 694;
    case MOONRISE_1:
        return 851;
    case MORRIS:
        return 673;
    case MORTIS:
        return 691;
    case MOSAICO:
        return 204;
    case MOSSQUARTZ:
        return 862;
    case MOTHERBOARD:
        return 782;
    case MOUNTFUJI:
        return 1094;
    case MUD_SPEC:
        return 1243;
    case MUDDER:
        return 90;
    case MUERTOS:
        return 404;
    case MUMMYSROT:
        return 1252;
    case MURKY:
        return 382;
    case MUSICBOX:
        return 820;
    case NAGA:
        return 397;
    case NAVYMURANO:
        return 740;
    case NAVYSHEEN:
        return 822;
    case NEBULACRUSADER:
        return 496;
    case NECROJR:
        return 1137;
    case NECROPOS:
        return 538;
    case NEEDLEPOINT:
        return 10087;
    case NEMESIS:
        return 481;
    case NEO_NOIR:
        return 653;
    case NEO_NOIR_1:
        return 695;
    case NEO_NOIR_2:
        return 803;
    case NEO_NOIR_3:
        return 988;
    case NEONKIMONO:
        return 464;
    case NEONPLY:
        return 893;
    case NEONREVOLUTION:
        return 600;
    case NEONRIDER:
        return 433;
    case NEONRIDER_1:
        return 707;
    case NEOQUEEN:
        return 1233;
    case NEURALNET:
        return 477;
    case NEVERMORE:
        return 813;
    case NEWROOTS:
        return 930;
    case NIGHT:
        return 40;
    case NIGHTBORRE:
        return 863;
    case NIGHTHEIST:
        return 1006;
    case NIGHTOPS:
        return 236;
    case NIGHTRIOT:
        return 692;
    case NIGHTSTRIPE:
        return 735;
    case NIGHTTERROR:
        return 1130;
    case NIGHTMARE:
        return 714;
    case NIGHTSHADE:
        return 223;
    case NIGHTWISH:
        return 1141;
    case NITRO:
        return 254;
    case NITRO_1:
        return 322;
    case NITRO_2:
        return 798;
    case NOCTS:
        return 10076;
    case NOSTALGIA:
        return 911;
    case NUCLEARGARDEN:
        return 372;
    case NUCLEARGARDEN_1:
        return 789;
    case NUCLEARTHREAT:
        return 168;
    case NUCLEARTHREAT_1:
        return 179;
    case NUCLEARWASTE:
        return 369;
    case OBSIDIAN:
        return 894;
    case OCEANDRIVE:
        return 1090;
    case OCEANFOAM:
        return 211;
    case OCEANFOAM_1:
        return 213;
    case OCEANIC:
        return 550;
    case OCEANIC_1:
        return 682;
    case OFFWORLD:
        return 680;
    case OFFWORLD_1:
        return 849;
    case OILCHANGE:
        return 1086;
    case OLRUSTY:
        return 966;
    case OLDROOTS:
        return 931;
    case OLIVEPLAID:
        return 365;
    case OMEGA:
        return 10047;
    case ONITAIJI:
        return 662;
    case ORANGEANOLIS:
        return 922;
    case ORANGECRASH:
        return 545;
    case ORANGEDDPAT:
        return 83;
    case ORANGEFILIGREE:
        return 743;
    case ORANGEKIMONO:
        return 465;
    case ORANGEMURANO:
        return 738;
    case ORANGEPEEL:
        return 141;
    case ORBITMK01:
        return 656;
    case ORIGAMI:
        return 434;
    case ORION:
        return 313;
    case OSCILLATOR:
        return 1049;
    case OSIPR:
        return 1042;
    case OSIRIS:
        return 349;
    case OSSIFIED:
        return 36;
    case OUTBREAK:
        return 518;
    case OVERGROWTH:
        return 183;
    case OVERPRINT:
        return 10054;
    case OVERTAKE:
        return 10043;
    case OXIDEBLAZE:
        return 645;
    case OXIDEBLAZE_1:
        return 706;
    case OXIDEBLAZE_2:
        return 808;
    case OXIDEOASIS:
        return 923;
    case PALM:
        return 157;
    case PALM_1:
        return 201;
    case PANDORASBOX:
        return 448;
    case PANDORASBOX_1:
        return 10037;
    case PANTHER:
        return 276;
    case PANTHERCAMO:
        return 1019;
    case PANTHERAONCA:
        return 1018;
    case PARAGREEN:
        return 454;
    case PARALLAX:
        return 989;
    case PARCHED:
        return 880;
    case PATHFINDER:
        return 443;
    case PAW:
        return 718;
    case PETROGLYPH:
        return 608;
    case PHANTOM:
        return 686;
    case PHANTOMDISRUPTOR:
        return 941;
    case PHOBOS:
        return 584;
    case PHOENIXBLACKLIGHT:
        return 1013;
    case PHOENIXCHALK:
        return 1010;
    case PHOENIXMARKER:
        return 1011;
    case PHOENIXSTENCIL:
        return 1012;
    case PHOSPHOR:
        return 810;
    case PHOTICZONE:
        return 526;
    case PILOT:
        return 347;
    case PINKDDPAT:
        return 84;
    case PIPEDOWN:
        return 812;
    case PITVIPER:
        return 251;
    case PLAGUE:
        return 1088;
    case PLASTIQUE:
        return 916;
    case PLAYERTWO:
        return 946;
    case PLUME:
        return 890;
    case POINTDISARRAY:
        return 506;
    case POISONDART:
        return 315;
    case POLARCAMO:
        return 74;
    case POLARMESH:
        return 107;
    case POLEPOSITION:
        return 435;
    case POLYMAG:
        return 1149;
    case POLYGON:
        return 10052;
    case POLYMER:
        return 622;
    case POPAWP:
        return 1058;
    case POPDOG:
        return 909;
    case POSEIDON:
        return 449;
    case POULTRYGEIST:
        return 1139;
    case POW:
        return 10049;
    case POWERLOADER:
        return 514;
    case POWERCORE:
        return 612;
    case POWERCORE_1:
        return 719;
    case PRAETORIAN:
        return 535;
    case PREDATOR:
        return 170;
    case PREY:
        return 935;
    case PRIMALSABER:
        return 556;
    case PRIMECONSPIRACY:
        return 999;
    case PRINTSTREAM:
        return 962;
    case PRINTSTREAM_1:
        return 984;
    case PRINTSTREAM_2:
        return 1142;
    case PRISMTERRACE:
        return 1072;
    case PROPAGANDA:
        return 1067;
    case PROTOTYPE:
        return 950;
    case PULSE:
        return 260;
    case PULSE_1:
        return 287;
    case PULSE_2:
        return 338;
    case PURPLEDDPAT:
        return 818;
    case PYRE:
        return 860;
    case QUEENJAGUAR:
        return 10071;
    case QUICKSAND:
        return 929;
    case QUICKSILVER:
        return 407;
    case RACINGGREEN:
        return 10044;
    case RADIATIONHAZARD:
        return 167;
    case RADIATIONHAZARD_1:
        return 375;
    case RAMESESREACH:
        return 1240;
    case RANDOMACCESS:
        return 779;
    case RANGEEN:
        return 498;
    case RANGER:
        return 484;
    case RAPIDEYEMOVEMENT:
        return 1127;
    case RATROD:
        return 885;
    case RATTLER:
        return 10059;
    case RE_ENTRY:
        return 555;
    case REACTOR:
        return 367;
    case REBEL:
        return 1235;
    case REBOOT:
        return 595;
    case REBUILT:
        return 1230;
    case REDASTOR:
        return 543;
    case REDDDPAT:
        return 926;
    case REDFILIGREE:
        return 742;
    case REDFRAGCAM:
        return 275;
    case REDLAMINATE:
        return 14;
    case REDLEATHER:
        return 348;
    case REDPYTHON:
        return 320;
    case REDQUARTZ:
        return 248;
    case REDROCK:
        return 668;
    case REDSTONE:
        return 762;
    case REDTIRE:
        return 1079;
    case REDLINE:
        return 259;
    case REDLINE_1:
        return 282;
    case REMOTECONTROL:
        return 791;
    case RETRIBUTION:
        return 307;
    case RETROBUTION:
        return 510;
    case REZANTHERED:
        return 10069;
    case RICOCHET:
        return 507;
    case RIOT:
        return 488;
    case RIPPLE:
        return 650;
    case RISINGSKULL:
        return 263;
    case ROADRASH:
        return 318;
    case ROADBLOCK:
        return 1157;
    case ROCKETPOP:
        return 478;
    case ROLLCAGE:
        return 604;
    case ROSEIRON:
        return 262;
    case ROYALBLUE:
        return 332;
    case ROYALCONSORTS:
        return 625;
    case ROYALLEGION:
        return 532;
    case ROYALPALADIN:
        return 512;
    case RUBYPOISONDART:
        return 482;
    case RUNANDHIDE:
        return 1000;
    case RUNIC:
        return 973;
    case RUSTCOAT:
        return 203;
    case RUSTCOAT_1:
        return 323;
    case RUSTCOAT_2:
        return 414;
    case RUSTCOAT_3:
        return 754;
    case RUSTLEAF:
        return 733;
    case SACRIFICE:
        return 918;
    case SAFARIMESH:
        return 72;
    case SAFETYNET:
        return 795;
    case SAGESPRAY:
        return 119;
    case SAKKAKU:
        return 1229;
    case SANDDASHED:
        return 148;
    case SANDDUNE:
        return 99;
    case SANDDUNE_1:
        return 208;
    case SANDMESH:
        return 116;
    case SANDSCALE:
        return 630;
    case SANDSPRAY:
        return 124;
    case SANDSTORM:
        return 823;
    case SANDSTORM_1:
        return 264;
    case SANDSTORM_2:
        return 289;
    case SCAFFOLD:
        return 652;
    case SCARABRUSH:
        return 1250;
    case SCARLETSHAMAGH:
        return 10075;
    case SCAVENGER:
        return 806;
    case SCHEMATIC:
        return 1074;
    case SCORCHED:
        return 175;
    case SCORPION:
        return 71;
    case SCRAWL:
        return 1128;
    case SCUMBRIA:
        return 505;
    case SCUMBRIA_1:
        return 605;
    case SEACALICO:
        return 868;
    case SEABIRD:
        return 473;
    case SEABIRD_1:
        return 873;
    case SEASONS:
        return 654;
    case SEEYALATER:
        return 678;
    case SERENITY:
        return 405;
    case SERGEANT:
        return 288;
    case SERUM:
        return 221;
    case SETTINGSUN:
        return 368;
    case SHALLOWGRAVE:
        return 636;
    case SHAPEWOOD:
        return 516;
    case SHATTERED:
        return 192;
    case SHIPPINGFORECAST:
        return 452;
    case SHRED:
        return 710;
    case SIENNADAMASK:
        return 826;
    case SIGNAL:
        return 807;
    case SILKTIGER:
        return 1029;
    case SILVER:
        return 32;
    case SILVERQUARTZ:
        return 252;
    case SKULLCRUSHER:
        return 843;
    case SKULLS:
        return 11;
    case SLASHED:
        return 304;
    case SLATE:
        return 1035;
    case SLAUGHTER:
        return 59;
    case SLAUGHTER_1:
        return 10021;
    case SLIDE:
        return 755;
    case SLINGSHOT:
        return 10073;
    case SLIPSTREAM:
        return 616;
    case SMOKEOUT:
        return 10078;
    case SNACKATTACK:
        return 1100;
    case SNAKECAMO:
        return 30;
    case SNAKEPIT:
        return 1249;
    case SNAKEBITE:
        return 10007;
    case SNEK_9:
        return 722;
    case SNOWLEOPARD:
        return 10070;
    case SOBEKSBITE:
        return 1247;
    case SONAR:
        return 633;
    case SPACECAT:
        return 1125;
    case SPACERACE:
        return 1055;
    case SPALTEDWOOD:
        return 927;
    case SPEARMINT:
        return 10026;
    case SPECIALDELIVERY:
        return 500;
    case SPECTRE:
        return 547;
    case SPIDERLILY:
        return 1097;
    case SPIRITBOARD:
        return 1140;
    case SPITFIRE:
        return 194;
    case SPLASH:
        return 162;
    case SPLASHJAM:
        return 165;
    case SPRINGTWILLY:
        return 1060;
    case SPRUCEDDPAT:
        return 10010;
    case SPUTNIK:
        return 1056;
    case STAINED:
        return 43;
    case STAINEDGLASS:
        return 867;
    case STAINLESS:
        return 277;
    case STALKER:
        return 898;
    case STARLIGHTPROTECTOR:
        return 1134;
    case STEELDELTA:
        return 1238;
    case STEELDISRUPTION:
        return 230;
    case STINGER:
        return 628;
    case STONECOLD:
        return 494;
    case STONEMOSAICO:
        return 865;
    case STORM:
        return 100;
    case STRATS:
        return 1075;
    case STYMPHALIAN:
        return 690;
    case STYX:
        return 371;
    case SUBMERGED:
        return 1242;
    case SUGARRUSH:
        return 661;
    case SUNINLEO:
        return 451;
    case SUNBAKED:
        return 1246;
    case SUNDOWN:
        return 869;
    case SUNSETLILY:
        return 726;
    case SUNSETSTORM壱:
        return 469;
    case SUNSETSTORM弐:
        return 470;
    case SUPERCONDUCTOR:
        return 10018;
    case SUPERNOVA:
        return 358;
    case SURFWOOD:
        return 871;
    case SURVEILLANCE:
        return 995;
    case SURVIVALIST:
        return 721;
    case SURVIVORZ:
        return 492;
    case SWAG_7:
        return 703;
    case SWEEPER:
        return 794;
    case SWITCHBOARD:
        return 998;
    case SYDMEAD:
        return 601;
    case SYNDICATE:
        return 1064;
    case SYNTHLEAF:
        return 732;
    case SYSTEMLOCK:
        return 401;
    case TACTICAT:
        return 687;
    case TALLGRASS:
        return 1023;
    case TARGETACQUIRED:
        return 1027;
    case TATTER:
        return 337;
    case TEALBLOSSOM:
        return 728;
    case TEARDOWN:
        return 244;
    case TECLUBURNER:
        return 521;
    case TEMPEST:
        return 191;
    case TEMUKAU:
        return 1228;
    case TERRACE:
        return 463;
    case TERRAIN:
        return 285;
    case THEBATTLESTAR:
        return 533;
    case THEBRONZE:
        return 992;
    case THECOALITION:
        return 1063;
    case THEEMPEROR:
        return 844;
    case THEEMPRESS:
        return 675;
    case THEEXECUTIONER:
        return 511;
    case THEFUSCHIAISNOW:
        return 269;
    case THEKRAKEN:
        return 256;
    case THEPRINCE:
        return 736;
    case THETRAITOR:
        return 1040;
    case THREATDETECTED:
        return 996;
    case TICKETTOHELL:
        return 1136;
    case TIGERMOTH:
        return 519;
    case TIGERPIT:
        return 1015;
    case TIGERSTRIKE:
        return 10067;
    case TIGERTOOTH:
        return 409;
    case TIGRIS:
        return 350;
    case TITANIUMBIT:
        return 272;
    case TOMCAT:
        return 942;
    case TOOTHFAIRY:
        return 971;
    case TORN:
        return 896;
    case TORNADO:
        return 101;
    case TORNADO_1:
        return 206;
    case TORQUE:
        return 305;
    case TORQUE_1:
        return 489;
    case TOXIC:
        return 374;
    case TOYSOLDIER:
        return 716;
    case TOYBOX:
        return 1098;
    case TRACTION:
        return 717;
    case TRANQUILITY:
        return 393;
    case TRANSPORT:
        return 10051;
    case TRAVELER:
        return 363;
    case TREAD:
        return 1091;
    case TREADPLATE:
        return 268;
    case TRIARCH:
        return 613;
    case TRIGGERDISCIPLINE:
        return 1050;
    case TRIGON:
        return 283;
    case TRIQUA:
        return 674;
    case TRIUMVIRATE:
        return 530;
    case TROPICALSTORM:
        return 233;
    case TURBOPEEK:
        return 1101;
    case TURF:
        return 635;
    case TURTLE:
        return 10050;
    case TUXEDO:
        return 297;
    case TWILIGHTGALAXY:
        return 437;
    case TWINTURBO:
        return 747;
    case TWIST:
        return 334;
    case ULTRALIGHT:
        return 958;
    case ULTRAVIOLET:
        return 98;
    case ULTRAVIOLET_1:
        return 620;
    case ULTRAVIOLET_2:
        return 621;
    case UMBRALRABBIT:
        return 1227;
    case UNCHARTED:
        return 836;
    case UNDERTOW:
        return 271;
    case UNHINGED:
        return 10088;
    case URBANDASHED:
        return 149;
    case URBANDDPAT:
        return 17;
    case URBANHAZARD:
        return 354;
    case URBANHAZARD_1:
        return 387;
    case URBANHAZARD_2:
        return 700;
    case URBANMASKED:
        return 143;
    case URBANPERFORATED:
        return 135;
    case URBANRUBBLE:
        return 237;
    case URBANSHOCK:
        return 396;
    case VALENCE:
        return 426;
    case VALENCE_1:
        return 529;
    case VANDAL:
        return 981;
    case VARICAMO:
        return 235;
    case VARICAMOBLUE:
        return 238;
    case VAULTHEIST:
        return 1007;
    case VENDETTA:
        return 976;
    case VENTRUSH:
        return 1154;
    case VENTILATOR:
        return 606;
    case VENTILATORS:
        return 544;
    case VERDANTGROWTH:
        return 828;
    case VERDIGRIS:
        return 848;
    case VICE:
        return 10048;
    case VICTORIA:
        return 270;
    case VINOPRIMO:
        return 749;
    case VIOLENTDAIMYO:
        return 585;
    case VIOLETMURANO:
        return 739;
    case VIRUS:
        return 20;
    case VISIONS:
        return 1153;
    case VOGUE:
        return 963;
    case VULCAN:
        return 302;
    case WALNUT:
        return 158;
    case WARBIRD:
        return 900;
    case WARHAWK:
        return 713;
    case WASTELANDPRINCESS:
        return 638;
    case WASTELANDREBEL:
        return 380;
    case WASTELANDREBEL_1:
        return 586;
    case WATCHDOG:
        return 1103;
    case WATERELEMENTAL:
        return 353;
    case WATERSIGIL:
        return 224;
    case WATERSOFNEPHTHYS:
        return 1241;
    case WAVESPRAY:
        return 186;
    case WAVESPERFORATED:
        return 136;
    case WEASEL:
        return 607;
    case WELCOMETOTHEJUNGLE:
        return 1001;
    case WHITEFISH:
        return 840;
    case WHITEOUT:
        return 102;
    case WHITEOUT_1:
        return 1065;
    case WICKEDSICK:
        return 1224;
    case WILDCHILD:
        return 1236;
    case WILDLILY:
        return 734;
    case WILDLOTUS:
        return 724;
    case WILDSIX:
        return 699;
    case WILDFIRE:
        return 917;
    case WINDBLOWN:
        return 1051;
    case WINGS:
        return 73;
    case WINGSHOT:
        return 501;
    case WINTERFOREST:
        return 76;
    case WINTERIZED:
        return 1158;
    case WITHEREDVINE:
        return 932;
    case WOODFIRED:
        return 809;
    case WOODSMAN:
        return 667;
    case WORMGOD:
        return 424;
    case WRAITHS:
        return 495;
    case X_RAY:
        return 125;
    case X_RAY_1:
        return 215;
    case X_RAY_2:
        return 1004;
    case XIANGLIU:
        return 643;
    case XOXO:
        return 1046;
    case YELLOWJACKET:
        return 476;
    case YELLOW_BANDED:
        return 10086;
    case YORICK:
        return 517;
    case ZANDER:
        return 655;
    case ZIGGY:
        return 689;
    case ZIRKA:
        return 187;
    case ZOMBIEOFFENSIVE:
        return 1135;
    case ZXSPECTRON:
        return 1092;
    case DRAGONKING:
        return 400;
    }
}

