#pragma once

#include "../valve/weapon.h"
#include "../core/interfaces.h"
#include "../core/settings.h"
#include "../valve/centity.h"

#include <iostream>

namespace skins
{
	void change();

	void change_knife_model();

	void update();

	void pop_skin_list();
	
	int get_list_index(CWeapon_Entity* weapon_entity);

    int skinEnumToID(int SkinEnum);

    inline const char* skin_list[1147]{
        "3rd Commando Company",
        "Abyss",
        "Abyssal Apparition",
        "Acheron",
        "Acid Etched",
        "Acid Fade",
        "Acid Wash",
        "Aerial",
        "Afterimage",
        "Agent",
        "Airlock",
        "Akihabara Accept",
        "Akoben",
        "Akoben_1",
        "Allure",
        "Aloha",
        "Aloha_1",
        "Amber Fade",
        "Amber Fade_1",
        "Amber Slipstream",
        "Amphibious",
        "Ancient Earth",
        "Ancient Lore",
        "Ancient Ritual",
        "Ancient Visions",
        "Angry Mob",
        "Anodized Gunmetal",
        "Anodized Navy",
        "Anodized Navy_1",
        "Anolis",
        "Antique",
        "Antique_1",
        "Apeps Curse",
        "Apocalypto",
        "Aqua Terrace",
        "Aquamarine Revenge",
        "Arboreal",
        "Arctic Camo",
        "Arctic Wolf",
        "Arctic Wolf_1",
        "Arid",
        "Aristocrat",
        "Armor Core",
        "Army Mesh",
        "Army Recon",
        "Army Sheen",
        "Ash Wood",
        "Asiimov",
        "Asiimov_1",
        "Asiimov_2",
        "Asiimov_3",
        "Asiimov_4",
        "Assault",
        "Asterion",
        "Astral Jörmungandr",
        "Atheris",
        "Atlas",
        "Atomic Alloy",
        "Autotronic",
        "Autotronic_1",
        "Autotronic_2",
        "Autotronic_3",
        "Autotronic_4",
        "Autotronic_5",
        "Autotronic_6",
        "Autotronic_7",
        "Autotronic_8",
        "Autotronic_9",
        "Autumn Twilly",
        "Avalanche",
        "Aztec",
        "Azure Glyph",
        "Azure Zebra",
        "Badlands",
        "Balance",
        "Bamboo Forest",
        "Bamboo Garden",
        "Bamboo Print",
        "Bamboo Shadow",
        "Bamboozle",
        "Banana Cannon",
        "Banana Leaf",
        "Baroque Orange",
        "Baroque Purple",
        "Baroque Red",
        "Barricade",
        "Basilisk",
        "Bengal Tiger",
        "Bengal Tiger_1",
        "Berries And Cherries",
        "BI83 Spectrum",
        "Big Game",
        "Big Iron",
        "Bioleak",
        "Black & Tan",
        "Black Laminat_10",
        "Black Laminate",
        "Black Laminate_1",
        "Black Laminate_2",
        "Black Laminate_3",
        "Black Laminate_4",
        "Black Laminate_5",
        "Black Laminate_6",
        "Black Laminate_7",
        "Black Laminate_8",
        "Black Laminate_9",
        "Black Limba",
        "Black Lotus",
        "Black Nile",
        "Black Sand",
        "Black Sand_1",
        "Black Sand_2",
        "Black Sand_3",
        "Black Tie",
        "Black Tie_1",
        "Blast From the Past",
        "Blaze",
        "Blaze Orange",
        "Bleached",
        "Blind Spot",
        "Blizzard Marbleized",
        "Blood in the Water",
        "Blood Pressure",
        "Blood Tiger",
        "Bloodshot",
        "Bloodsport",
        "Bloodsport_1",
        "Bloodsport_2",
        "Bloomstick",
        "Blue Fissure",
        "Blue Laminate",
        "Blue Phosphor",
        "Blue Ply",
        "Blue Spruce",
        "Blue Steel",
        "Blue Streak",
        "Blue Tire",
        "Blue Titanium",
        "Blueprint",
        "Blueprint_1",
        "Bone Forged",
        "Bone Machine",
        "Bone Mask",
        "Bone Pile",
        "BOOM",
        "Boom",
        "Boost Protocol",
        "Boreal Forest",
        "Boroque Sand",
        "Brake Light",
        "Brass",
        "Bratatat",
        "Breaker Box",
        "Briar",
        "Briefing",
        "Briefing_1",
        "Bright Water",
        "Bright Water_1",
        "Bright Water_2",
        "Bronze Deco",
        "Bronze Morph",
        "Bronzed",
        "Brother",
        "Buckshot",
        "Buddy",
        "Bulkhead",
        "Bulldozer",
        "Bullet Queen",
        "Bullet Rain",
        "Bunsen Burner",
        "Business Class",
        "Button Masher",
        "Buzz Kill",
        "Caged Steel",
        "Caiman",
        "Calf Skin",
        "CaliCamo",
        "Canal Spray",
        "Candy Apple",
        "Candy Apple_1",
        "Capillary",
        "Capillary_1",
        "Capillary_2",
        "Caramel",
        "Carbon Fiber",
        "Cardiac",
        "Carnivore",
        "Cartel",
        "Cartel_1",
        "Cartel_2",
        "Carved Jade",
        "Case Hardened",
        "Case Hardened_1",
        "Cassette",
        "Catacombs",
        "CAUTION",
        "CAUTION_1",
        "Cerberus",
        "Chainmail",
        "Chalice",
        "Chameleon",
        "Chanticos Fire",
        "Charred",
        "Charter",
        "Chatterbox",
        "Check Engine",
        "Chemical Green",
        "Chopper",
        "Chromatic Aberration",
        "Chromatic Aberration_1",
        "Chronos",
        "Cinquedea",
        "Circaetus",
        "Cirrus",
        "Classic Crate",
        "Clay Ambush",
        "Clear Polymer",
        "Clear Polymer_1",
        "Co_Processor",
        "Coach Class",
        "Cobalt Core",
        "Cobalt Disruption",
        "Cobalt Halftone",
        "Cobalt Quartz",
        "Cobalt Skulls",
        "Cobra Strike",
        "Cocoa Rampage",
        "Code Red",
        "Cold Blooded",
        "Cold Fusion",
        "Colony",
        "Colony IV",
        "Commemoration",
        "Commuter",
        "Condemned",
        "Condition Zero",
        "Connexion",
        "Conspiracy",
        "Constrictor",
        "Containment Breach",
        "Contaminant",
        "Contamination",
        "Contractor",
        "Contrast Spray",
        "Control Panel",
        "Converter",
        "Convoy",
        "Cool Mint",
        "Coolant",
        "Copper",
        "Copper Borre",
        "Copper Coated",
        "Copper Galaxy",
        "Copperhead",
        "Core Breach",
        "Corinthian",
        "Corporal",
        "Cortex",
        "Corticera",
        "Corticera_1",
        "Counter Terrace",
        "Cracked Opal",
        "Crazy 8",
        "Crime Scene",
        "Crimson Blossom",
        "Crimson Kimono",
        "Crimson Kimono_1",
        "Crimson Tsunami",
        "Crimson Weave",
        "Crimson Web",
        "Crimson Web_1",
        "Crimson Web_2",
        "Crypsis",
        "Curse",
        "Cut Out",
        "Cyanospatter",
        "Cyber Security",
        "Cyber Shell",
        "Cyberforce",
        "Cyrex",
        "Cyrex_1",
        "Cyrex_2",
        "Cyrex_3",
        "Daedalus",
        "Damascus Steel",
        "Damascus Steel_1",
        "Damascus Steel_2",
        "Damascus Steel_3",
        "Damascus Steel_4",
        "Danger Close",
        "Dark Age",
        "Dark Blossom",
        "Dark Filigree",
        "Dark Water",
        "Darkwing",
        "Dart",
        "Day Lily",
        "Daybreak",
        "Dazzle",
        "Deadly Poison",
        "Death by Kitty",
        "Death by Puppy",
        "Death Grip",
        "Death Rattle",
        "Death Strike",
        "Deaths Head",
        "Decimator",
        "Decimator_1",
        "Decommissioned",
        "Deep Relief",
        "Delusion",
        "Demeter",
        "Demolition",
        "Desert Blossom",
        "Desert Brush",
        "Desert DDPAT",
        "Desert Hydra",
        "Desert Shamagh",
        "Desert Storm",
        "Desert Strike",
        "Desert Tactical",
        "Desert Warfare",
        "Desert_Strike",
        "Desert_Strike_1",
        "Desolate Space",
        "Destroyer",
        "Detour",
        "dev_texture",
        "Devourer",
        "Dezastre",
        "Diamondback",
        "Digital Architect",
        "Digital Mesh",
        "Directive",
        "Dirt Drop",
        "Disco Tech",
        "Dispatch",
        "Distressed",
        "Djinn",
        "Doomkitty",
        "Dopple_10",
        "Dopple_11",
        "Dopple_12",
        "Dopple_13",
        "Doppler",
        "Doppler_1",
        "Doppler_2",
        "Doppler_3",
        "Doppler_4",
        "Doppler_5",
        "Doppler_6",
        "Doppler_7",
        "Doppler_8",
        "Doppler_9",
        "Downtown",
        "Dragon Lore",
        "Dragon Tattoo",
        "Dragon Tech",
        "Dragonfire",
        "Dream Glade",
        "Drift Wood",
        "Drop Me",
        "Drought",
        "Dry Season",
        "Dualing Dragons",
        "Duality",
        "Duct Tape",
        "Duelist",
        "Dusk Ruins",
        "Echoing Sands",
        "Eclipse",
        "Eco",
        "Eco_1",
        "Electric Hive",
        "Elegant Vines",
        "Elite 16",
        "Elite Build",
        "Elite Build_1",
        "Elite Build_2",
        "Embargo",
        "Emerald",
        "Emerald Dragon",
        "Emerald Jörmungandr",
        "Emerald Pinstripe",
        "Emerald Poison Dart",
        "Emerald Quartz",
        "Emerald Web",
        "Emerald_1",
        "Emerald_2",
        "Emphorosaur_S",
        "Enforcer",
        "Ensnared",
        "Entombed",
        "Evil Daimyo",
        "Exchanger",
        "Exo",
        "Exoskeleton",
        "Exposure",
        "Eye of Athena",
        "Eye of Horus",
        "Facets",
        "Facility Dark",
        "Facility Draft",
        "Facility Negative",
        "Facility Sketch",
        "Fade",
        "Fade_1",
        "Fade_2",
        "Fade_3",
        "Fade_4",
        "Fade_5",
        "Faded Zebra",
        "Fairy Tale",
        "Fall Hazard",
        "Fallout Warning",
        "Fallout Warning_1",
        "Faulty Wiring",
        "Featherweight",
        "Fennec Fox",
        "Fever Dream",
        "Fever Dream_1",
        "Field Agent",
        "Finish Line",
        "Fire Elemental",
        "Fire Serpent",
        "Firefight",
        "Firestarter",
        "First Class",
        "First Class_1",
        "Fizzy POP",
        "Flame Jörmungandr",
        "Flame Test",
        "Flash Out",
        "Flashback",
        "Flashback_1",
        "Fleet Flock",
        "Flora Carnivora",
        "Flux",
        "Food Chain",
        "Foresight",
        "Forest DDPAT",
        "Forest DDPAT_1",
        "Forest Leaves",
        "Forest Night",
        "Foundation",
        "Fowl Play",
        "Fragments",
        "Framework",
        "Franklin",
        "Franklin_1",
        "Freehand",
        "Freehand_1",
        "Freehand_2",
        "Freight",
        "Frontside Misty",
        "Frost Borre",
        "Fubar",
        "Fubar_1",
        "Fuel Injector",
        "Fuel Injector_1",
        "Fuel Rod",
        "Full Stop",
        "Gamma Doppler",
        "Gamma Doppler_1",
        "Gamma Doppler_2",
        "Gamma Doppler_3",
        "Gamma Doppler_4",
        "Gamma Doppler_5",
        "Gamma Doppler_6",
        "Gamma Doppler_7",
        "Gamma Doppler_8",
        "Gamma Doppler_9",
        "Gator Mesh",
        "Gauss",
        "Ghost Camo",
        "Ghost Crusader",
        "Gila",
        "Giraffe",
        "Glacier Mesh",
        "Global Offensive",
        "Gnarled",
        "Gold Arabesque",
        "Gold Bismuth",
        "Gold Brick",
        "Golden Coil",
        "Golden Koi",
        "Goo",
        "Grand Prix",
        "Granite Marbleized",
        "Graphite",
        "Graphite_1",
        "Grassland",
        "Grassland Leaves",
        "Graven",
        "Green Apple",
        "Green Laminate",
        "Green Marine",
        "Green Plaid",
        "Griffin",
        "Grim",
        "Grinder",
        "Grip",
        "Grotto",
        "Groundwater",
        "Groundwater_1",
        "Guardian",
        "Guardian_1",
        "Guerrilla",
        "Guerrilla_1",
        "Gungnir",
        "Gunsmoke",
        "Hades",
        "Hand Brake",
        "Hand Cannon",
        "Handgun",
        "Hard Water",
        "Harvester",
        "Hazard",
        "Hazard Pay",
        "Head Shot",
        "Heat",
        "Heat_1",
        "Heaven Guard",
        "Heaven Guard_1",
        "Heavy Metal",
        "Hedge Maze",
        "Heirloom",
        "Heist",
        "Hellfire",
        "Hemoglobin",
        "Hexane",
        "Hieroglyph",
        "High Beam",
        "High Roller",
        "High Seas",
        "Highwayman",
        "Hive",
        "Hot Rod",
        "Hot Rod_1",
        "Hot Shot",
        "Hot Snakes",
        "Houndstooth",
        "Howl",
        "Humidor",
        "Hunter",
        "Hunting Blind",
        "Hydra",
        "Hydroponic",
        "Hyper Beast",
        "Hyper Beast_1",
        "Hyper Beast_2",
        "Hyper Beast_3",
        "Hypnotic",
        "Icarus Fell",
        "Ice Cap",
        "Ice Coaled",
        "Imminent Danger",
        "Impact Drill",
        "Imperial",
        "Imperial Dragon",
        "Imperial Plaid",
        "Impire",
        "Imprint",
        "In Living Color",
        "Incinegator",
        "Indigo",
        "Inferno",
        "Infrastructure",
        "Inlay",
        "Insomnia",
        "Integrale",
        "Interlock",
        "Iron Clad",
        "Ironwork",
        "Irradiated Alert",
        "Isaac",
        "Ivory",
        "Jade",
        "Jaguar",
        "Jambiya",
        "Jet Set",
        "Judgement of Anubis",
        "Jungle",
        "Jungle Dashed",
        "Jungle DDPAT",
        "Jungle Slipstream",
        "Jungle Slipstream_1",
        "Jungle Spray",
        "Jungle Thicket",
        "Jungle Tiger",
        "Jungle_1",
        "Junk Yard",
        "Justice",
        "Kami",
        "Kami_1",
        "Keeping Tabs",
        "Kill Confirmed",
        "King Snake",
        "Kiss♥Love",
        "Kitbash",
        "Knight",
        "Koi",
        "Kumicho Dragon",
        "Lab Rats",
        "Labyrinth",
        "Lapis Gator",
        "Last Dive",
        "Lead Conduit",
        "Leaded Glass",
        "Leather",
        "Leather_1",
        "Leet Museo",
        "Legion of Anubis",
        "Lichen Dashed",
        "Lifted Spirits",
        "Light Rail",
        "Lightning Strike",
        "Limelight",
        "Lionfish",
        "Liquidation",
        "Llama Cannon",
        "Lore",
        "Lore_1",
        "Lore_2",
        "Lore_3",
        "Lore_4",
        "Lore_5",
        "Lore_6",
        "Lore_7",
        "Lore_8",
        "Lore_9",
        "Loudmouth",
        "Lt Commander",
        "Lumen",
        "Lunar Weave",
        "Lush Ruins",
        "Macabre",
        "Magma",
        "Magna Carta",
        "Magnesium",
        "Mainframe",
        "Mainframe 001",
        "Malachite",
        "Man_o_war",
        "Man_o_war_1",
        "Mandrel",
        "Mangrove",
        "Marble Fade",
        "Marble Fade_1",
        "Marble Fade_2",
        "Marina",
        "Master Piece",
        "Mayan Dreams",
        "Mecha Industries",
        "Mecha Industries_1",
        "Mecha Industries_2",
        "Mechanism",
        "Medusa",
        "Mehndi",
        "Melondrama",
        "Meltdown",
        "Memento",
        "Memento_1",
        "Meow 36",
        "Metal Flowers",
        "Metallic DDPAT",
        "Meteorite",
        "Midnight Lily",
        "Midnight Palm",
        "Midnight Storm",
        "Minotaurs Labyrinth",
        "Mint Kimono",
        "Mischief",
        "Mjölnir",
        "Modern Hunter",
        "Modest Threat",
        "Module",
        "Mogul",
        "Momentum",
        "Momentum_1",
        "Monkey Business",
        "Monkeyflage",
        "Monster Call",
        "Monster Mashup",
        "Moon in Libra",
        "Moonrise",
        "Moonrise_1",
        "Morris",
        "Mortis",
        "Mosaico",
        "Moss Quartz",
        "Motherboard",
        "Mount Fuji",
        "Mud_Spec",
        "Mudder",
        "Muertos",
        "Mummys Rot",
        "Murky",
        "Music Box",
        "Naga",
        "Navy Murano",
        "Navy Sheen",
        "Nebula Crusader",
        "Necro Jr",
        "Necropos",
        "Needle Point",
        "Nemesis",
        "Neo_Noir",
        "Neo_Noir_1",
        "Neo_Noir_2",
        "Neo_Noir_3",
        "Neon Kimono",
        "Neon Ply",
        "Neon Revolution",
        "Neon Rider",
        "Neon Rider_1",
        "Neoqueen",
        "Neural Net",
        "Nevermore",
        "New Roots",
        "Night",
        "Night Borre",
        "Night Heist",
        "Night Ops",
        "Night Riot",
        "Night Stripe",
        "Night Terror",
        "Nightmare",
        "Nightshade",
        "Nightwish",
        "Nitro",
        "Nitro_1",
        "Nitro_2",
        "Nocts",
        "Nostalgia",
        "Nuclear Garden",
        "Nuclear Garden_1",
        "Nuclear Threat",
        "Nuclear Threat_1",
        "Nuclear Waste",
        "Obsidian",
        "Ocean Drive",
        "Ocean Foam",
        "Ocean Foam_1",
        "Oceanic",
        "Oceanic_1",
        "Off World",
        "Off World_1",
        "Oil Change",
        "Ol Rusty",
        "Old Roots",
        "Olive Plaid",
        "Omega",
        "Oni Taiji",
        "Orange Anolis",
        "Orange Crash",
        "Orange DDPAT",
        "Orange Filigree",
        "Orange Kimono",
        "Orange Murano",
        "Orange Peel",
        "Orbit Mk01",
        "Origami",
        "Orion",
        "Oscillator",
        "OSIPR",
        "Osiris",
        "Ossified",
        "Outbreak",
        "Overgrowth",
        "Overprint",
        "Overtake",
        "Oxide Blaze",
        "Oxide Blaze_1",
        "Oxide Blaze_2",
        "Oxide Oasis",
        "Palm",
        "Palm_1",
        "Pandoras Box",
        "Pandoras Box_1",
        "Panther",
        "Panther Camo",
        "Panthera onca",
        "Para Green",
        "Parallax",
        "Parched",
        "Pathfinder",
        "PAW",
        "Petroglyph",
        "Phantom",
        "Phantom Disruptor",
        "Phobos",
        "Phoenix Blacklight",
        "Phoenix Chalk",
        "Phoenix Marker",
        "Phoenix Stencil",
        "Phosphor",
        "Photic Zone",
        "Pilot",
        "Pink DDPAT",
        "Pipe Down",
        "Pit Viper",
        "Plague",
        "Plastique",
        "Player Two",
        "Plume",
        "Point Disarray",
        "Poison Dart",
        "Polar Camo",
        "Polar Mesh",
        "Pole Position",
        "Poly Mag",
        "Polygon",
        "Polymer",
        "POP AWP",
        "Popdog",
        "Poseidon",
        "Poultrygeist",
        "POW",
        "Power Loader",
        "Powercore",
        "Powercore_1",
        "Praetorian",
        "Predator",
        "Prey",
        "Primal Saber",
        "Prime Conspiracy",
        "Printstream",
        "Printstream_1",
        "Printstream_2",
        "Prism Terrace",
        "Propaganda",
        "Prototype",
        "Pulse",
        "Pulse_1",
        "Pulse_2",
        "Purple DDPAT",
        "Pyre",
        "Queen Jaguar",
        "Quick Sand",
        "Quicksilver",
        "Racing Green",
        "Radiation Hazard",
        "Radiation Hazard_1",
        "Rameses Reach",
        "Random Access",
        "Rangeen",
        "Ranger",
        "Rapid Eye Movement",
        "Rat Rod",
        "Rattler",
        "Re_Entry",
        "Reactor",
        "Rebel",
        "Reboot",
        "Rebuilt",
        "Red Astor",
        "Red DDPAT",
        "Red Filigree",
        "Red FragCam",
        "Red Laminate",
        "Red Leather",
        "Red Python",
        "Red Quartz",
        "Red Rock",
        "Red Stone",
        "Red Tire",
        "Redline",
        "Redline_1",
        "Remote Control",
        "Retribution",
        "Retrobution",
        "Rezan the Red",
        "Ricochet",
        "Riot",
        "Ripple",
        "Rising Skull",
        "Road Rash",
        "Roadblock",
        "Rocket Pop",
        "Roll Cage",
        "Rose Iron",
        "Royal Blue",
        "Royal Consorts",
        "Royal Legion",
        "Royal Paladin",
        "Ruby Poison Dart",
        "Run and Hide",
        "Runic",
        "Rust Coat",
        "Rust Coat_1",
        "Rust Coat_2",
        "Rust Coat_3",
        "Rust Leaf",
        "Sacrifice",
        "Safari Mesh",
        "Safety Net",
        "Sage Spray",
        "Sakkaku",
        "Sand Dashed",
        "Sand Dune",
        "Sand Dune_1",
        "Sand Mesh",
        "Sand Scale",
        "Sand Spray",
        "Sand Storm",
        "Sandstorm",
        "Sandstorm_1",
        "Scaffold",
        "ScaraB Rush",
        "Scarlet Shamagh",
        "Scavenger",
        "Schematic",
        "Scorched",
        "Scorpion",
        "Scrawl",
        "Scumbria",
        "Scumbria_1",
        "Sea Calico",
        "Seabird",
        "Seabird_1",
        "Seasons",
        "See Ya Later",
        "Serenity",
        "Sergeant",
        "Serum",
        "Setting Sun",
        "Shallow Grave",
        "Shapewood",
        "Shattered",
        "Shipping Forecast",
        "Shred",
        "Sienna Damask",
        "Signal",
        "Silk Tiger",
        "Silver",
        "Silver Quartz",
        "Skull Crusher",
        "Skulls",
        "Slashed",
        "Slate",
        "Slaughter",
        "Slaughter_1",
        "Slide",
        "Slingshot",
        "Slipstream",
        "Smoke Out",
        "Snack Attack",
        "Snake Camo",
        "Snake Pit",
        "Snakebite",
        "Snek_9",
        "Snow Leopard",
        "Sobeks Bite",
        "Sonar",
        "Space Cat",
        "Space Race",
        "Spalted Wood",
        "Spearmint",
        "Special Delivery",
        "Spectre",
        "Spider Lily",
        "Spirit Board",
        "Spitfire",
        "Splash",
        "Splash Jam",
        "Spring Twilly",
        "Spruce DDPAT",
        "Sputnik",
        "Stained",
        "Stained Glass",
        "Stainless",
        "Stalker",
        "Starlight Protector",
        "Steel Delta",
        "Steel Disruption",
        "Stinger",
        "Stone Cold",
        "Stone Mosaico",
        "Storm",
        "Strats",
        "Stymphalian",
        "Styx",
        "Submerged",
        "Sugar Rush",
        "Sun in Leo",
        "Sunbaked",
        "Sundown",
        "Sunset Lily",
        "Sunset Storm 壱",
        "Sunset Storm 弐",
        "Superconductor",
        "Supernova",
        "Surfwood",
        "Surveillance",
        "Survivalist",
        "Survivor Z",
        "SWAG_7",
        "Sweeper",
        "Switch Board",
        "Syd Mead",
        "Syndicate",
        "Synth Leaf",
        "System Lock",
        "Tacticat",
        "Tall Grass",
        "Target Acquired",
        "Tatter",
        "Teal Blossom",
        "Teardown",
        "Teclu Burner",
        "Tempest",
        "Temukau",
        "Terrace",
        "Terrain",
        "The Battlestar",
        "The Bronze",
        "The Coalition",
        "The Emperor",
        "The Empress",
        "The Executioner",
        "The Fuschia Is Now",
        "The Kraken",
        "The Prince",
        "The Traitor",
        "Threat Detected",
        "Ticket to Hell",
        "Tiger Moth",
        "Tiger Pit",
        "Tiger Strike",
        "Tiger Tooth",
        "Tigris",
        "Titanium Bit",
        "Tom Cat",
        "Tooth Fairy",
        "Torn",
        "Tornado",
        "Tornado_1",
        "Torque",
        "Torque_1",
        "Toxic",
        "Toy Soldier",
        "Toybox",
        "Traction",
        "Tranquility",
        "Transport",
        "Traveler",
        "Tread",
        "Tread Plate",
        "Triarch",
        "Trigger Discipline",
        "Trigon",
        "Triqua",
        "Triumvirate",
        "Tropical Storm",
        "Turbo Peek",
        "Turf",
        "Turtle",
        "Tuxedo",
        "Twilight Galaxy",
        "Twin Turbo",
        "Twist",
        "Ultralight",
        "Ultraviolet",
        "Ultraviolet_1",
        "Ultraviolet_2",
        "Umbral Rabbit",
        "Uncharted",
        "Undertow",
        "Unhinged",
        "Urban Dashed",
        "Urban DDPAT",
        "Urban Hazard",
        "Urban Hazard_1",
        "Urban Hazard_2",
        "Urban Masked",
        "Urban Perforated",
        "Urban Rubble",
        "Urban Shock",
        "Valence",
        "Valence_1",
        "Vandal",
        "VariCamo",
        "VariCamo Blue",
        "Vault Heist",
        "Vendetta",
        "Vent Rush",
        "Ventilator",
        "Ventilators",
        "Verdant Growth",
        "Verdigris",
        "Vice",
        "Victoria",
        "Vino Primo",
        "Violent Daimyo",
        "Violet Murano",
        "Virus",
        "Visions",
        "Vogue",
        "Vulcan",
        "Walnut",
        "Warbird",
        "Warhawk",
        "Wasteland Princess",
        "Wasteland Rebel",
        "Wasteland Rebel_1",
        "Watchdog",
        "Water Elemental",
        "Water Sigil",
        "Waters of Nephthys",
        "Wave Spray",
        "Waves Perforated",
        "Weasel",
        "Welcome to the Jungle",
        "Whitefish",
        "Whiteout",
        "Whiteout_1",
        "Wicked Sick",
        "Wild Child",
        "Wild Lily",
        "Wild Lotus",
        "Wild Six",
        "Wildfire",
        "Windblown",
        "Wings",
        "Wingshot",
        "Winter Forest",
        "Winterized",
        "Withered Vine",
        "Wood Fired",
        "Woodsman",
        "Worm God",
        "Wraiths",
        "X_Ray",
        "X_Ray_1",
        "X_Ray_2",
        "Xiangliu",
        "XOXO",
        "Yellow Jacket",
        "Yellow_banded",
        "Yorick",
        "Zander",
        "Ziggy",
        "Zirka",
        "Zombie Offensive",
        "ZX Spectron",
        "Dragon King"
    };
}

enum skinEnum {
    THIRDRDCOMMANDOCOMPANY,
    ABYSS,
    ABYSSALAPPARITION,
    ACHERON,
    ACIDETCHED,
    ACIDFADE,
    ACIDWASH,
    AERIAL,
    AFTERIMAGE,
    AGENT,
    AIRLOCK,
    AKIHABARAACCEPT,
    AKOBEN,
    AKOBEN_1,
    ALLURE,
    ALOHA,
    ALOHA_1,
    AMBERFADE,
    AMBERFADE_1,
    AMBERSLIPSTREAM,
    AMPHIBIOUS,
    ANCIENTEARTH,
    ANCIENTLORE,
    ANCIENTRITUAL,
    ANCIENTVISIONS,
    ANGRYMOB,
    ANODIZEDGUNMETAL,
    ANODIZEDNAVY,
    ANODIZEDNAVY_1,
    ANOLIS,
    ANTIQUE,
    ANTIQUE_1,
    APEPSCURSE,
    APOCALYPTO,
    AQUATERRACE,
    AQUAMARINEREVENGE,
    ARBOREAL,
    ARCTICCAMO,
    ARCTICWOLF,
    ARCTICWOLF_1,
    ARID,
    ARISTOCRAT,
    ARMORCORE,
    ARMYMESH,
    ARMYRECON,
    ARMYSHEEN,
    ASHWOOD,
    ASIIMOV,
    ASIIMOV_1,
    ASIIMOV_2,
    ASIIMOV_3,
    ASIIMOV_4,
    ASSAULT,
    ASTERION,
    ASTRALJÖRMUNGANDR,
    ATHERIS,
    ATLAS,
    ATOMICALLOY,
    AUTOTRONIC,
    AUTOTRONIC_1,
    AUTOTRONIC_2,
    AUTOTRONIC_3,
    AUTOTRONIC_4,
    AUTOTRONIC_5,
    AUTOTRONIC_6,
    AUTOTRONIC_7,
    AUTOTRONIC_8,
    AUTOTRONIC_9,
    AUTUMNTWILLY,
    AVALANCHE,
    AZTEC,
    AZUREGLYPH,
    AZUREZEBRA,
    BADLANDS,
    BALANCE,
    BAMBOOFOREST,
    BAMBOOGARDEN,
    BAMBOOPRINT,
    BAMBOOSHADOW,
    BAMBOOZLE,
    BANANACANNON,
    BANANALEAF,
    BAROQUEORANGE,
    BAROQUEPURPLE,
    BAROQUERED,
    BARRICADE,
    BASILISK,
    BENGALTIGER,
    BENGALTIGER_1,
    BERRIESANDCHERRIES,
    BI83SPECTRUM,
    BIGGAME,
    BIGIRON,
    BIOLEAK,
    BLACKTAN,
    BLACKLAMINAT_10,
    BLACKLAMINATE,
    BLACKLAMINATE_1,
    BLACKLAMINATE_2,
    BLACKLAMINATE_3,
    BLACKLAMINATE_4,
    BLACKLAMINATE_5,
    BLACKLAMINATE_6,
    BLACKLAMINATE_7,
    BLACKLAMINATE_8,
    BLACKLAMINATE_9,
    BLACKLIMBA,
    BLACKLOTUS,
    BLACKNILE,
    BLACKSAND,
    BLACKSAND_1,
    BLACKSAND_2,
    BLACKSAND_3,
    BLACKTIE,
    BLACKTIE_1,
    BLASTFROMTHEPAST,
    BLAZE,
    BLAZEORANGE,
    BLEACHED,
    BLINDSPOT,
    BLIZZARDMARBLEIZED,
    BLOODINTHEWATER,
    BLOODPRESSURE,
    BLOODTIGER,
    BLOODSHOT,
    BLOODSPORT,
    BLOODSPORT_1,
    BLOODSPORT_2,
    BLOOMSTICK,
    BLUEFISSURE,
    BLUELAMINATE,
    BLUEPHOSPHOR,
    BLUEPLY,
    BLUESPRUCE,
    BLUESTEEL,
    BLUESTREAK,
    BLUETIRE,
    BLUETITANIUM,
    BLUEPRINT,
    BLUEPRINT_1,
    BONEFORGED,
    BONEMACHINE,
    BONEMASK,
    BONEPILE,
    BOOM,
    BOOME,
    BOOSTPROTOCOL,
    BOREALFOREST,
    BOROQUESAND,
    BRAKELIGHT,
    BRASS,
    BRATATAT,
    BREAKERBOX,
    BRIAR,
    BRIEFING,
    BRIEFING_1,
    BRIGHTWATER,
    BRIGHTWATER_1,
    BRIGHTWATER_2,
    BRONZEDECO,
    BRONZEMORPH,
    BRONZED,
    BROTHER,
    BUCKSHOT,
    BUDDY,
    BULKHEAD,
    BULLDOZER,
    BULLETQUEEN,
    BULLETRAIN,
    BUNSENBURNER,
    BUSINESSCLASS,
    BUTTONMASHER,
    BUZZKILL,
    CAGEDSTEEL,
    CAIMAN,
    CALFSKIN,
    CALICAMO,
    CANALSPRAY,
    CANDYAPPLE,
    CANDYAPPLE_1,
    CAPILLARY,
    CAPILLARY_1,
    CAPILLARY_2,
    CARAMEL,
    CARBONFIBER,
    CARDIAC,
    CARNIVORE,
    CARTEL,
    CARTEL_1,
    CARTEL_2,
    CARVEDJADE,
    CASEHARDENED,
    CASEHARDENED_1,
    CASSETTE,
    CATACOMBS,
    CAUTION,
    CAUTION_1,
    CERBERUS,
    CHAINMAIL,
    CHALICE,
    CHAMELEON,
    CHANTICOSFIRE,
    CHARRED,
    CHARTER,
    CHATTERBOX,
    CHECKENGINE,
    CHEMICALGREEN,
    CHOPPER,
    CHROMATICABERRATION,
    CHROMATICABERRATION_1,
    CHRONOS,
    CINQUEDEA,
    CIRCAETUS,
    CIRRUS,
    CLASSICCRATE,
    CLAYAMBUSH,
    CLEARPOLYMER,
    CLEARPOLYMER_1,
    CO_PROCESSOR,
    COACHCLASS,
    COBALTCORE,
    COBALTDISRUPTION,
    COBALTHALFTONE,
    COBALTQUARTZ,
    COBALTSKULLS,
    COBRASTRIKE,
    COCOARAMPAGE,
    CODERED,
    COLDBLOODED,
    COLDFUSION,
    COLONY,
    COLONYIV,
    COMMEMORATION,
    COMMUTER,
    CONDEMNED,
    CONDITIONZERO,
    CONNEXION,
    CONSPIRACY,
    CONSTRICTOR,
    CONTAINMENTBREACH,
    CONTAMINANT,
    CONTAMINATION,
    CONTRACTOR,
    CONTRASTSPRAY,
    CONTROLPANEL,
    CONVERTER,
    CONVOY,
    COOLMINT,
    COOLANT,
    COPPER,
    COPPERBORRE,
    COPPERCOATED,
    COPPERGALAXY,
    COPPERHEAD,
    COREBREACH,
    CORINTHIAN,
    CORPORAL,
    CORTEX,
    CORTICERA,
    CORTICERA_1,
    COUNTERTERRACE,
    CRACKEDOPAL,
    CRAZY8,
    CRIMESCENE,
    CRIMSONBLOSSOM,
    CRIMSONKIMONO,
    CRIMSONKIMONO_1,
    CRIMSONTSUNAMI,
    CRIMSONWEAVE,
    CRIMSONWEB,
    CRIMSONWEB_1,
    CRIMSONWEB_2,
    CRYPSIS,
    CURSE,
    CUTOUT,
    CYANOSPATTER,
    CYBERSECURITY,
    CYBERSHELL,
    CYBERFORCE,
    CYREX,
    CYREX_1,
    CYREX_2,
    CYREX_3,
    DAEDALUS,
    DAMASCUSSTEEL,
    DAMASCUSSTEEL_1,
    DAMASCUSSTEEL_2,
    DAMASCUSSTEEL_3,
    DAMASCUSSTEEL_4,
    DANGERCLOSE,
    DARKAGE,
    DARKBLOSSOM,
    DARKFILIGREE,
    DARKWATER,
    DARKWING,
    DART,
    DAYLILY,
    DAYBREAK,
    DAZZLE,
    DEADLYPOISON,
    DEATHBYKITTY,
    DEATHBYPUPPY,
    DEATHGRIP,
    DEATHRATTLE,
    DEATHSTRIKE,
    DEATHSHEAD,
    DECIMATOR,
    DECIMATOR_1,
    DECOMMISSIONED,
    DEEPRELIEF,
    DELUSION,
    DEMETER,
    DEMOLITION,
    DESERTBLOSSOM,
    DESERTBRUSH,
    DESERTDDPAT,
    DESERTHYDRA,
    DESERTSHAMAGH,
    DESERTSTORM,
    DESERTSTRIKE,
    DESERTTACTICAL,
    DESERTWARFARE,
    DESERT_STRIKE,
    DESERT_STRIKE_1,
    DESOLATESPACE,
    DESTROYER,
    DETOUR,
    DEV_TEXTURE,
    DEVOURER,
    DEZASTRE,
    DIAMONDBACK,
    DIGITALARCHITECT,
    DIGITALMESH,
    DIRECTIVE,
    DIRTDROP,
    DISCOTECH,
    DISPATCH,
    DISTRESSED,
    DJINN,
    DOOMKITTY,
    DOPPLE_10,
    DOPPLE_11,
    DOPPLE_12,
    DOPPLE_13,
    DOPPLER,
    DOPPLER_1,
    DOPPLER_2,
    DOPPLER_3,
    DOPPLER_4,
    DOPPLER_5,
    DOPPLER_6,
    DOPPLER_7,
    DOPPLER_8,
    DOPPLER_9,
    DOWNTOWN,
    DRAGONLORE,
    DRAGONTATTOO,
    DRAGONTECH,
    DRAGONFIRE,
    DREAMGLADE,
    DRIFTWOOD,
    DROPME,
    DROUGHT,
    DRYSEASON,
    DUALINGDRAGONS,
    DUALITY,
    DUCTTAPE,
    DUELIST,
    DUSKRUINS,
    ECHOINGSANDS,
    ECLIPSE,
    ECO,
    ECO_1,
    ELECTRICHIVE,
    ELEGANTVINES,
    ELITE16,
    ELITEBUILD,
    ELITEBUILD_1,
    ELITEBUILD_2,
    EMBARGO,
    EMERALD,
    EMERALDDRAGON,
    EMERALDJÖRMUNGANDR,
    EMERALDPINSTRIPE,
    EMERALDPOISONDART,
    EMERALDQUARTZ,
    EMERALDWEB,
    EMERALD_1,
    EMERALD_2,
    EMPHOROSAUR_S,
    ENFORCER,
    ENSNARED,
    ENTOMBED,
    EVILDAIMYO,
    EXCHANGER,
    EXO,
    EXOSKELETON,
    EXPOSURE,
    EYEOFATHENA,
    EYEOFHORUS,
    FACETS,
    FACILITYDARK,
    FACILITYDRAFT,
    FACILITYNEGATIVE,
    FACILITYSKETCH,
    FADE,
    FADE_1,
    FADE_2,
    FADE_3,
    FADE_4,
    FADE_5,
    FADEDZEBRA,
    FAIRYTALE,
    FALLHAZARD,
    FALLOUTWARNING,
    FALLOUTWARNING_1,
    FAULTYWIRING,
    FEATHERWEIGHT,
    FENNECFOX,
    FEVERDREAM,
    FEVERDREAM_1,
    FIELDAGENT,
    FINISHLINE,
    FIREELEMENTAL,
    FIRESERPENT,
    FIREFIGHT,
    FIRESTARTER,
    FIRSTCLASS,
    FIRSTCLASS_1,
    FIZZYPOP,
    FLAMEJÖRMUNGANDR,
    FLAMETEST,
    FLASHOUT,
    FLASHBACK,
    FLASHBACK_1,
    FLEETFLOCK,
    FLORACARNIVORA,
    FLUX,
    FOODCHAIN,
    FORESIGHT,
    FORESTDDPAT,
    FORESTDDPAT_1,
    FORESTLEAVES,
    FORESTNIGHT,
    FOUNDATION,
    FOWLPLAY,
    FRAGMENTS,
    FRAMEWORK,
    FRANKLIN,
    FRANKLIN_1,
    FREEHAND,
    FREEHAND_1,
    FREEHAND_2,
    FREIGHT,
    FRONTSIDEMISTY,
    FROSTBORRE,
    FUBAR,
    FUBAR_1,
    FUELINJECTOR,
    FUELINJECTOR_1,
    FUELROD,
    FULLSTOP,
    GAMMADOPPLER,
    GAMMADOPPLER_1,
    GAMMADOPPLER_2,
    GAMMADOPPLER_3,
    GAMMADOPPLER_4,
    GAMMADOPPLER_5,
    GAMMADOPPLER_6,
    GAMMADOPPLER_7,
    GAMMADOPPLER_8,
    GAMMADOPPLER_9,
    GATORMESH,
    GAUSS,
    GHOSTCAMO,
    GHOSTCRUSADER,
    GILA,
    GIRAFFE,
    GLACIERMESH,
    GLOBALOFFENSIVE,
    GNARLED,
    GOLDARABESQUE,
    GOLDBISMUTH,
    GOLDBRICK,
    GOLDENCOIL,
    GOLDENKOI,
    GOO,
    GRANDPRIX,
    GRANITEMARBLEIZED,
    GRAPHITE,
    GRAPHITE_1,
    GRASSLAND,
    GRASSLANDLEAVES,
    GRAVEN,
    GREENAPPLE,
    GREENLAMINATE,
    GREENMARINE,
    GREENPLAID,
    GRIFFIN,
    GRIM,
    GRINDER,
    GRIP,
    GROTTO,
    GROUNDWATER,
    GROUNDWATER_1,
    GUARDIAN,
    GUARDIAN_1,
    GUERRILLA,
    GUERRILLA_1,
    GUNGNIR,
    GUNSMOKE,
    HADES,
    HANDBRAKE,
    HANDCANNON,
    HANDGUN,
    HARDWATER,
    HARVESTER,
    HAZARD,
    HAZARDPAY,
    HEADSHOT,
    HEAT,
    HEAT_1,
    HEAVENGUARD,
    HEAVENGUARD_1,
    HEAVYMETAL,
    HEDGEMAZE,
    HEIRLOOM,
    HEIST,
    HELLFIRE,
    HEMOGLOBIN,
    HEXANE,
    HIEROGLYPH,
    HIGHBEAM,
    HIGHROLLER,
    HIGHSEAS,
    HIGHWAYMAN,
    HIVE,
    HOTROD,
    HOTROD_1,
    HOTSHOT,
    HOTSNAKES,
    HOUNDSTOOTH,
    HOWL,
    HUMIDOR,
    HUNTER,
    HUNTINGBLIND,
    HYDRA,
    HYDROPONIC,
    HYPERBEAST,
    HYPERBEAST_1,
    HYPERBEAST_2,
    HYPERBEAST_3,
    HYPNOTIC,
    ICARUSFELL,
    ICECAP,
    ICECOALED,
    IMMINENTDANGER,
    IMPACTDRILL,
    IMPERIAL,
    IMPERIALDRAGON,
    IMPERIALPLAID,
    IMPIRE,
    IMPRINT,
    INLIVINGCOLOR,
    INCINEGATOR,
    INDIGO,
    INFERNO,
    INFRASTRUCTURE,
    INLAY,
    INSOMNIA,
    INTEGRALE,
    INTERLOCK,
    IRONCLAD,
    IRONWORK,
    IRRADIATEDALERT,
    ISAAC,
    IVORY,
    JADE,
    JAGUAR,
    JAMBIYA,
    JETSET,
    JUDGEMENTOFANUBIS,
    JUNGLE,
    JUNGLEDASHED,
    JUNGLEDDPAT,
    JUNGLESLIPSTREAM,
    JUNGLESLIPSTREAM_1,
    JUNGLESPRAY,
    JUNGLETHICKET,
    JUNGLETIGER,
    JUNGLE_1,
    JUNKYARD,
    JUSTICE,
    KAMI,
    KAMI_1,
    KEEPINGTABS,
    KILLCONFIRMED,
    KINGSNAKE,
    KISSLOVE,
    KITBASH,
    KNIGHT,
    KOI,
    KUMICHODRAGON,
    LABRATS,
    LABYRINTH,
    LAPISGATOR,
    LASTDIVE,
    LEADCONDUIT,
    LEADEDGLASS,
    LEATHER,
    LEATHER_1,
    LEETMUSEO,
    LEGIONOFANUBIS,
    LICHENDASHED,
    LIFTEDSPIRITS,
    LIGHTRAIL,
    LIGHTNINGSTRIKE,
    LIMELIGHT,
    LIONFISH,
    LIQUIDATION,
    LLAMACANNON,
    LORE,
    LORE_1,
    LORE_2,
    LORE_3,
    LORE_4,
    LORE_5,
    LORE_6,
    LORE_7,
    LORE_8,
    LORE_9,
    LOUDMOUTH,
    LTCOMMANDER,
    LUMEN,
    LUNARWEAVE,
    LUSHRUINS,
    MACABRE,
    MAGMA,
    MAGNACARTA,
    MAGNESIUM,
    MAINFRAME,
    MAINFRAME001,
    MALACHITE,
    MAN_O_WAR,
    MAN_O_WAR_1,
    MANDREL,
    MANGROVE,
    MARBLEFADE,
    MARBLEFADE_1,
    MARBLEFADE_2,
    MARINA,
    MASTERPIECE,
    MAYANDREAMS,
    MECHAINDUSTRIES,
    MECHAINDUSTRIES_1,
    MECHAINDUSTRIES_2,
    MECHANISM,
    MEDUSA,
    MEHNDI,
    MELONDRAMA,
    MELTDOWN,
    MEMENTO,
    MEMENTO_1,
    MEOW36,
    METALFLOWERS,
    METALLICDDPAT,
    METEORITE,
    MIDNIGHTLILY,
    MIDNIGHTPALM,
    MIDNIGHTSTORM,
    MINOTAURSLABYRINTH,
    MINTKIMONO,
    MISCHIEF,
    MJÖLNIR,
    MODERNHUNTER,
    MODESTTHREAT,
    MODULE,
    MOGUL,
    MOMENTUM,
    MOMENTUM_1,
    MONKEYBUSINESS,
    MONKEYFLAGE,
    MONSTERCALL,
    MONSTERMASHUP,
    MOONINLIBRA,
    MOONRISE,
    MOONRISE_1,
    MORRIS,
    MORTIS,
    MOSAICO,
    MOSSQUARTZ,
    MOTHERBOARD,
    MOUNTFUJI,
    MUD_SPEC,
    MUDDER,
    MUERTOS,
    MUMMYSROT,
    MURKY,
    MUSICBOX,
    NAGA,
    NAVYMURANO,
    NAVYSHEEN,
    NEBULACRUSADER,
    NECROJR,
    NECROPOS,
    NEEDLEPOINT,
    NEMESIS,
    NEO_NOIR,
    NEO_NOIR_1,
    NEO_NOIR_2,
    NEO_NOIR_3,
    NEONKIMONO,
    NEONPLY,
    NEONREVOLUTION,
    NEONRIDER,
    NEONRIDER_1,
    NEOQUEEN,
    NEURALNET,
    NEVERMORE,
    NEWROOTS,
    NIGHT,
    NIGHTBORRE,
    NIGHTHEIST,
    NIGHTOPS,
    NIGHTRIOT,
    NIGHTSTRIPE,
    NIGHTTERROR,
    NIGHTMARE,
    NIGHTSHADE,
    NIGHTWISH,
    NITRO,
    NITRO_1,
    NITRO_2,
    NOCTS,
    NOSTALGIA,
    NUCLEARGARDEN,
    NUCLEARGARDEN_1,
    NUCLEARTHREAT,
    NUCLEARTHREAT_1,
    NUCLEARWASTE,
    OBSIDIAN,
    OCEANDRIVE,
    OCEANFOAM,
    OCEANFOAM_1,
    OCEANIC,
    OCEANIC_1,
    OFFWORLD,
    OFFWORLD_1,
    OILCHANGE,
    OLRUSTY,
    OLDROOTS,
    OLIVEPLAID,
    OMEGA,
    ONITAIJI,
    ORANGEANOLIS,
    ORANGECRASH,
    ORANGEDDPAT,
    ORANGEFILIGREE,
    ORANGEKIMONO,
    ORANGEMURANO,
    ORANGEPEEL,
    ORBITMK01,
    ORIGAMI,
    ORION,
    OSCILLATOR,
    OSIPR,
    OSIRIS,
    OSSIFIED,
    OUTBREAK,
    OVERGROWTH,
    OVERPRINT,
    OVERTAKE,
    OXIDEBLAZE,
    OXIDEBLAZE_1,
    OXIDEBLAZE_2,
    OXIDEOASIS,
    PALM,
    PALM_1,
    PANDORASBOX,
    PANDORASBOX_1,
    PANTHER,
    PANTHERCAMO,
    PANTHERAONCA,
    PARAGREEN,
    PARALLAX,
    PARCHED,
    PATHFINDER,
    PAW,
    PETROGLYPH,
    PHANTOM,
    PHANTOMDISRUPTOR,
    PHOBOS,
    PHOENIXBLACKLIGHT,
    PHOENIXCHALK,
    PHOENIXMARKER,
    PHOENIXSTENCIL,
    PHOSPHOR,
    PHOTICZONE,
    PILOT,
    PINKDDPAT,
    PIPEDOWN,
    PITVIPER,
    PLAGUE,
    PLASTIQUE,
    PLAYERTWO,
    PLUME,
    POINTDISARRAY,
    POISONDART,
    POLARCAMO,
    POLARMESH,
    POLEPOSITION,
    POLYMAG,
    POLYGON,
    POLYMER,
    POPAWP,
    POPDOG,
    POSEIDON,
    POULTRYGEIST,
    POW,
    POWERLOADER,
    POWERCORE,
    POWERCORE_1,
    PRAETORIAN,
    PREDATOR,
    PREY,
    PRIMALSABER,
    PRIMECONSPIRACY,
    PRINTSTREAM,
    PRINTSTREAM_1,
    PRINTSTREAM_2,
    PRISMTERRACE,
    PROPAGANDA,
    PROTOTYPE,
    PULSE,
    PULSE_1,
    PULSE_2,
    PURPLEDDPAT,
    PYRE,
    QUEENJAGUAR,
    QUICKSAND,
    QUICKSILVER,
    RACINGGREEN,
    RADIATIONHAZARD,
    RADIATIONHAZARD_1,
    RAMESESREACH,
    RANDOMACCESS,
    RANGEEN,
    RANGER,
    RAPIDEYEMOVEMENT,
    RATROD,
    RATTLER,
    RE_ENTRY,
    REACTOR,
    REBEL,
    REBOOT,
    REBUILT,
    REDASTOR,
    REDDDPAT,
    REDFILIGREE,
    REDFRAGCAM,
    REDLAMINATE,
    REDLEATHER,
    REDPYTHON,
    REDQUARTZ,
    REDROCK,
    REDSTONE,
    REDTIRE,
    REDLINE,
    REDLINE_1,
    REMOTECONTROL,
    RETRIBUTION,
    RETROBUTION,
    REZANTHERED,
    RICOCHET,
    RIOT,
    RIPPLE,
    RISINGSKULL,
    ROADRASH,
    ROADBLOCK,
    ROCKETPOP,
    ROLLCAGE,
    ROSEIRON,
    ROYALBLUE,
    ROYALCONSORTS,
    ROYALLEGION,
    ROYALPALADIN,
    RUBYPOISONDART,
    RUNANDHIDE,
    RUNIC,
    RUSTCOAT,
    RUSTCOAT_1,
    RUSTCOAT_2,
    RUSTCOAT_3,
    RUSTLEAF,
    SACRIFICE,
    SAFARIMESH,
    SAFETYNET,
    SAGESPRAY,
    SAKKAKU,
    SANDDASHED,
    SANDDUNE,
    SANDDUNE_1,
    SANDMESH,
    SANDSCALE,
    SANDSPRAY,
    SANDSTORM,
    SANDSTORM_1,
    SANDSTORM_2,
    SCAFFOLD,
    SCARABRUSH,
    SCARLETSHAMAGH,
    SCAVENGER,
    SCHEMATIC,
    SCORCHED,
    SCORPION,
    SCRAWL,
    SCUMBRIA,
    SCUMBRIA_1,
    SEACALICO,
    SEABIRD,
    SEABIRD_1,
    SEASONS,
    SEEYALATER,
    SERENITY,
    SERGEANT,
    SERUM,
    SETTINGSUN,
    SHALLOWGRAVE,
    SHAPEWOOD,
    SHATTERED,
    SHIPPINGFORECAST,
    SHRED,
    SIENNADAMASK,
    SIGNAL,
    SILKTIGER,
    SILVER,
    SILVERQUARTZ,
    SKULLCRUSHER,
    SKULLS,
    SLASHED,
    SLATE,
    SLAUGHTER,
    SLAUGHTER_1,
    SLIDE,
    SLINGSHOT,
    SLIPSTREAM,
    SMOKEOUT,
    SNACKATTACK,
    SNAKECAMO,
    SNAKEPIT,
    SNAKEBITE,
    SNEK_9,
    SNOWLEOPARD,
    SOBEKSBITE,
    SONAR,
    SPACECAT,
    SPACERACE,
    SPALTEDWOOD,
    SPEARMINT,
    SPECIALDELIVERY,
    SPECTRE,
    SPIDERLILY,
    SPIRITBOARD,
    SPITFIRE,
    SPLASH,
    SPLASHJAM,
    SPRINGTWILLY,
    SPRUCEDDPAT,
    SPUTNIK,
    STAINED,
    STAINEDGLASS,
    STAINLESS,
    STALKER,
    STARLIGHTPROTECTOR,
    STEELDELTA,
    STEELDISRUPTION,
    STINGER,
    STONECOLD,
    STONEMOSAICO,
    STORM,
    STRATS,
    STYMPHALIAN,
    STYX,
    SUBMERGED,
    SUGARRUSH,
    SUNINLEO,
    SUNBAKED,
    SUNDOWN,
    SUNSETLILY,
    SUNSETSTORM壱,
    SUNSETSTORM弐,
    SUPERCONDUCTOR,
    SUPERNOVA,
    SURFWOOD,
    SURVEILLANCE,
    SURVIVALIST,
    SURVIVORZ,
    SWAG_7,
    SWEEPER,
    SWITCHBOARD,
    SYDMEAD,
    SYNDICATE,
    SYNTHLEAF,
    SYSTEMLOCK,
    TACTICAT,
    TALLGRASS,
    TARGETACQUIRED,
    TATTER,
    TEALBLOSSOM,
    TEARDOWN,
    TECLUBURNER,
    TEMPEST,
    TEMUKAU,
    TERRACE,
    TERRAIN,
    THEBATTLESTAR,
    THEBRONZE,
    THECOALITION,
    THEEMPEROR,
    THEEMPRESS,
    THEEXECUTIONER,
    THEFUSCHIAISNOW,
    THEKRAKEN,
    THEPRINCE,
    THETRAITOR,
    THREATDETECTED,
    TICKETTOHELL,
    TIGERMOTH,
    TIGERPIT,
    TIGERSTRIKE,
    TIGERTOOTH,
    TIGRIS,
    TITANIUMBIT,
    TOMCAT,
    TOOTHFAIRY,
    TORN,
    TORNADO,
    TORNADO_1,
    TORQUE,
    TORQUE_1,
    TOXIC,
    TOYSOLDIER,
    TOYBOX,
    TRACTION,
    TRANQUILITY,
    TRANSPORT,
    TRAVELER,
    TREAD,
    TREADPLATE,
    TRIARCH,
    TRIGGERDISCIPLINE,
    TRIGON,
    TRIQUA,
    TRIUMVIRATE,
    TROPICALSTORM,
    TURBOPEEK,
    TURF,
    TURTLE,
    TUXEDO,
    TWILIGHTGALAXY,
    TWINTURBO,
    TWIST,
    ULTRALIGHT,
    ULTRAVIOLET,
    ULTRAVIOLET_1,
    ULTRAVIOLET_2,
    UMBRALRABBIT,
    UNCHARTED,
    UNDERTOW,
    UNHINGED,
    URBANDASHED,
    URBANDDPAT,
    URBANHAZARD,
    URBANHAZARD_1,
    URBANHAZARD_2,
    URBANMASKED,
    URBANPERFORATED,
    URBANRUBBLE,
    URBANSHOCK,
    VALENCE,
    VALENCE_1,
    VANDAL,
    VARICAMO,
    VARICAMOBLUE,
    VAULTHEIST,
    VENDETTA,
    VENTRUSH,
    VENTILATOR,
    VENTILATORS,
    VERDANTGROWTH,
    VERDIGRIS,
    VICE,
    VICTORIA,
    VINOPRIMO,
    VIOLENTDAIMYO,
    VIOLETMURANO,
    VIRUS,
    VISIONS,
    VOGUE,
    VULCAN,
    WALNUT,
    WARBIRD,
    WARHAWK,
    WASTELANDPRINCESS,
    WASTELANDREBEL,
    WASTELANDREBEL_1,
    WATCHDOG,
    WATERELEMENTAL,
    WATERSIGIL,
    WATERSOFNEPHTHYS,
    WAVESPRAY,
    WAVESPERFORATED,
    WEASEL,
    WELCOMETOTHEJUNGLE,
    WHITEFISH,
    WHITEOUT,
    WHITEOUT_1,
    WICKEDSICK,
    WILDCHILD,
    WILDLILY,
    WILDLOTUS,
    WILDSIX,
    WILDFIRE,
    WINDBLOWN,
    WINGS,
    WINGSHOT,
    WINTERFOREST,
    WINTERIZED,
    WITHEREDVINE,
    WOODFIRED,
    WOODSMAN,
    WORMGOD,
    WRAITHS,
    X_RAY,
    X_RAY_1,
    X_RAY_2,
    XIANGLIU,
    XOXO,
    YELLOWJACKET,
    YELLOW_BANDED,
    YORICK,
    ZANDER,
    ZIGGY,
    ZIRKA,
    ZOMBIEOFFENSIVE,
    ZXSPECTRON,
    DRAGONKING
};

